// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: evaluator.proto
// Protobuf C++ Version: 6.31.1

#include "evaluator.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr PositionRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        fen_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR PositionRequest::PositionRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PositionRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PositionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PositionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PositionRequestDefaultTypeInternal() {}
  union {
    PositionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PositionRequestDefaultTypeInternal _PositionRequest_default_instance_;

inline constexpr EvaluationResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        policy_{},
        value_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EvaluationResponse::EvaluationResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EvaluationResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EvaluationResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EvaluationResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EvaluationResponseDefaultTypeInternal() {}
  union {
    EvaluationResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EvaluationResponseDefaultTypeInternal _EvaluationResponse_default_instance_;
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_evaluator_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_evaluator_2eproto = nullptr;
const ::uint32_t
    TableStruct_evaluator_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PositionRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PositionRequest, _impl_.fen_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::EvaluationResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::EvaluationResponse, _impl_.policy_),
        PROTOBUF_FIELD_OFFSET(::EvaluationResponse, _impl_.value_),
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::PositionRequest)},
        {5, sizeof(::EvaluationResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_PositionRequest_default_instance_._instance,
    &::_EvaluationResponse_default_instance_._instance,
};
const char descriptor_table_protodef_evaluator_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017evaluator.proto\"\036\n\017PositionRequest\022\013\n\003"
    "fen\030\001 \001(\t\"3\n\022EvaluationResponse\022\016\n\006polic"
    "y\030\001 \003(\002\022\r\n\005value\030\002 \001(\0022>\n\tEvaluator\0221\n\010E"
    "valuate\022\020.PositionRequest\032\023.EvaluationRe"
    "sponseb\006proto3"
};
static ::absl::once_flag descriptor_table_evaluator_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_evaluator_2eproto = {
    false,
    false,
    174,
    descriptor_table_protodef_evaluator_2eproto,
    "evaluator.proto",
    &descriptor_table_evaluator_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_evaluator_2eproto::offsets,
    file_level_enum_descriptors_evaluator_2eproto,
    file_level_service_descriptors_evaluator_2eproto,
};
// ===================================================================

class PositionRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PositionRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PositionRequest, _impl_._has_bits_);
};

PositionRequest::PositionRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PositionRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PositionRequest)
}
PROTOBUF_NDEBUG_INLINE PositionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::PositionRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        fen_(arena, from.fen_) {}

PositionRequest::PositionRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PositionRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PositionRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PositionRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:PositionRequest)
}
PROTOBUF_NDEBUG_INLINE PositionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        fen_(arena) {}

inline void PositionRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PositionRequest::~PositionRequest() {
  // @@protoc_insertion_point(destructor:PositionRequest)
  SharedDtor(*this);
}
inline void PositionRequest::SharedDtor(MessageLite& self) {
  PositionRequest& this_ = static_cast<PositionRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.fen_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PositionRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PositionRequest(arena);
}
constexpr auto PositionRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PositionRequest),
                                            alignof(PositionRequest));
}
constexpr auto PositionRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PositionRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PositionRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PositionRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PositionRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PositionRequest>(), &PositionRequest::ByteSizeLong,
              &PositionRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PositionRequest, _impl_._cached_size_),
          false,
      },
      &PositionRequest::kDescriptorMethods,
      &descriptor_table_evaluator_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PositionRequest_class_data_ =
        PositionRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PositionRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PositionRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PositionRequest_class_data_.tc_table);
  return PositionRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 27, 2>
PositionRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PositionRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PositionRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PositionRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string fen = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(PositionRequest, _impl_.fen_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string fen = 1;
    {PROTOBUF_FIELD_OFFSET(PositionRequest, _impl_.fen_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\3\0\0\0\0\0\0"
    "PositionRequest"
    "fen"
  }},
};
PROTOBUF_NOINLINE void PositionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:PositionRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.fen_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PositionRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PositionRequest& this_ = static_cast<const PositionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PositionRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PositionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:PositionRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string fen = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_fen().empty()) {
      const ::std::string& _s = this_._internal_fen();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PositionRequest.fen");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PositionRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PositionRequest::ByteSizeLong(const MessageLite& base) {
  const PositionRequest& this_ = static_cast<const PositionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PositionRequest::ByteSizeLong() const {
  const PositionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PositionRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string fen = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_fen().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_fen());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PositionRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PositionRequest*>(&to_msg);
  auto& from = static_cast<const PositionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PositionRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_fen().empty()) {
      _this->_internal_set_fen(from._internal_fen());
    } else {
      if (_this->_impl_.fen_.IsDefault()) {
        _this->_internal_set_fen("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PositionRequest::CopyFrom(const PositionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PositionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PositionRequest::InternalSwap(PositionRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fen_, &other->_impl_.fen_, arena);
}

::google::protobuf::Metadata PositionRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EvaluationResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<EvaluationResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EvaluationResponse, _impl_._has_bits_);
};

EvaluationResponse::EvaluationResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EvaluationResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:EvaluationResponse)
}
PROTOBUF_NDEBUG_INLINE EvaluationResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::EvaluationResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        policy_{visibility, arena, from.policy_} {}

EvaluationResponse::EvaluationResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EvaluationResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EvaluationResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EvaluationResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.value_ = from._impl_.value_;

  // @@protoc_insertion_point(copy_constructor:EvaluationResponse)
}
PROTOBUF_NDEBUG_INLINE EvaluationResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        policy_{visibility, arena} {}

inline void EvaluationResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
EvaluationResponse::~EvaluationResponse() {
  // @@protoc_insertion_point(destructor:EvaluationResponse)
  SharedDtor(*this);
}
inline void EvaluationResponse::SharedDtor(MessageLite& self) {
  EvaluationResponse& this_ = static_cast<EvaluationResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EvaluationResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EvaluationResponse(arena);
}
constexpr auto EvaluationResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(EvaluationResponse, _impl_.policy_) +
          decltype(EvaluationResponse::_impl_.policy_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(EvaluationResponse), alignof(EvaluationResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&EvaluationResponse::PlacementNew_,
                                 sizeof(EvaluationResponse),
                                 alignof(EvaluationResponse));
  }
}
constexpr auto EvaluationResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EvaluationResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EvaluationResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EvaluationResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EvaluationResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EvaluationResponse>(), &EvaluationResponse::ByteSizeLong,
              &EvaluationResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EvaluationResponse, _impl_._cached_size_),
          false,
      },
      &EvaluationResponse::kDescriptorMethods,
      &descriptor_table_evaluator_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EvaluationResponse_class_data_ =
        EvaluationResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EvaluationResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EvaluationResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EvaluationResponse_class_data_.tc_table);
  return EvaluationResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
EvaluationResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EvaluationResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    EvaluationResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::EvaluationResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float value = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 0, 0, PROTOBUF_FIELD_OFFSET(EvaluationResponse, _impl_.value_)}},
    // repeated float policy = 1;
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(EvaluationResponse, _impl_.policy_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float policy = 1;
    {PROTOBUF_FIELD_OFFSET(EvaluationResponse, _impl_.policy_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // float value = 2;
    {PROTOBUF_FIELD_OFFSET(EvaluationResponse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void EvaluationResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:EvaluationResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.policy_.Clear();
  _impl_.value_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EvaluationResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EvaluationResponse& this_ = static_cast<const EvaluationResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EvaluationResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EvaluationResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:EvaluationResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated float policy = 1;
  if (this_._internal_policy_size() > 0) {
    target = stream->WriteFixedPacked(1, this_._internal_policy(), target);
  }

  // float value = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_value()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_value(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EvaluationResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EvaluationResponse::ByteSizeLong(const MessageLite& base) {
  const EvaluationResponse& this_ = static_cast<const EvaluationResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EvaluationResponse::ByteSizeLong() const {
  const EvaluationResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:EvaluationResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated float policy = 1;
    {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_policy_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
   {
    // float value = 2;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_value()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EvaluationResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EvaluationResponse*>(&to_msg);
  auto& from = static_cast<const EvaluationResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:EvaluationResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_policy()->MergeFrom(from._internal_policy());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (::absl::bit_cast<::uint32_t>(from._internal_value()) != 0) {
      _this->_impl_.value_ = from._impl_.value_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EvaluationResponse::CopyFrom(const EvaluationResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EvaluationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EvaluationResponse::InternalSwap(EvaluationResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.policy_.InternalSwap(&other->_impl_.policy_);
  swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata EvaluationResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_evaluator_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
