// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: evaluator.proto
// Protobuf C++ Version: 6.31.1

#ifndef evaluator_2eproto_2epb_2eh
#define evaluator_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_evaluator_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_evaluator_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_evaluator_2eproto;
}  // extern "C"
class EvaluationResponse;
struct EvaluationResponseDefaultTypeInternal;
extern EvaluationResponseDefaultTypeInternal _EvaluationResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull EvaluationResponse_class_data_;
class PositionRequest;
struct PositionRequestDefaultTypeInternal;
extern PositionRequestDefaultTypeInternal _PositionRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PositionRequest_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class PositionRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PositionRequest) */ {
 public:
  inline PositionRequest() : PositionRequest(nullptr) {}
  ~PositionRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PositionRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PositionRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PositionRequest(::google::protobuf::internal::ConstantInitialized);

  inline PositionRequest(const PositionRequest& from) : PositionRequest(nullptr, from) {}
  inline PositionRequest(PositionRequest&& from) noexcept
      : PositionRequest(nullptr, ::std::move(from)) {}
  inline PositionRequest& operator=(const PositionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PositionRequest& operator=(PositionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PositionRequest& default_instance() {
    return *reinterpret_cast<const PositionRequest*>(
        &_PositionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PositionRequest& a, PositionRequest& b) { a.Swap(&b); }
  inline void Swap(PositionRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PositionRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PositionRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PositionRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PositionRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PositionRequest& from) { PositionRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PositionRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PositionRequest"; }

 protected:
  explicit PositionRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PositionRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PositionRequest& from);
  PositionRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PositionRequest&& from) noexcept
      : PositionRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFenFieldNumber = 1,
  };
  // string fen = 1;
  void clear_fen() ;
  const ::std::string& fen() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_fen(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_fen();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_fen();
  void set_allocated_fen(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_fen() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_fen(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_fen();

  public:
  // @@protoc_insertion_point(class_scope:PositionRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 27,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PositionRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr fen_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_evaluator_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PositionRequest_class_data_;
// -------------------------------------------------------------------

class EvaluationResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:EvaluationResponse) */ {
 public:
  inline EvaluationResponse() : EvaluationResponse(nullptr) {}
  ~EvaluationResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EvaluationResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EvaluationResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EvaluationResponse(::google::protobuf::internal::ConstantInitialized);

  inline EvaluationResponse(const EvaluationResponse& from) : EvaluationResponse(nullptr, from) {}
  inline EvaluationResponse(EvaluationResponse&& from) noexcept
      : EvaluationResponse(nullptr, ::std::move(from)) {}
  inline EvaluationResponse& operator=(const EvaluationResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline EvaluationResponse& operator=(EvaluationResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EvaluationResponse& default_instance() {
    return *reinterpret_cast<const EvaluationResponse*>(
        &_EvaluationResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(EvaluationResponse& a, EvaluationResponse& b) { a.Swap(&b); }
  inline void Swap(EvaluationResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EvaluationResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EvaluationResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EvaluationResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EvaluationResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EvaluationResponse& from) { EvaluationResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EvaluationResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "EvaluationResponse"; }

 protected:
  explicit EvaluationResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  EvaluationResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EvaluationResponse& from);
  EvaluationResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, EvaluationResponse&& from) noexcept
      : EvaluationResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPolicyFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // repeated float policy = 1;
  int policy_size() const;
  private:
  int _internal_policy_size() const;

  public:
  void clear_policy() ;
  float policy(int index) const;
  void set_policy(int index, float value);
  void add_policy(float value);
  const ::google::protobuf::RepeatedField<float>& policy() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_policy();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_policy() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_policy();

  public:
  // float value = 2;
  void clear_value() ;
  float value() const;
  void set_value(float value);

  private:
  float _internal_value() const;
  void _internal_set_value(float value);

  public:
  // @@protoc_insertion_point(class_scope:EvaluationResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const EvaluationResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> policy_;
    float value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_evaluator_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull EvaluationResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PositionRequest

// string fen = 1;
inline void PositionRequest::clear_fen() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fen_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& PositionRequest::fen() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PositionRequest.fen)
  return _internal_fen();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PositionRequest::set_fen(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.fen_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PositionRequest.fen)
}
inline ::std::string* PROTOBUF_NONNULL PositionRequest::mutable_fen()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_fen();
  // @@protoc_insertion_point(field_mutable:PositionRequest.fen)
  return _s;
}
inline const ::std::string& PositionRequest::_internal_fen() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fen_.Get();
}
inline void PositionRequest::_internal_set_fen(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.fen_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PositionRequest::_internal_mutable_fen() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.fen_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PositionRequest::release_fen() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PositionRequest.fen)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.fen_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fen_.Set("", GetArena());
  }
  return released;
}
inline void PositionRequest::set_allocated_fen(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.fen_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fen_.IsDefault()) {
    _impl_.fen_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PositionRequest.fen)
}

// -------------------------------------------------------------------

// EvaluationResponse

// repeated float policy = 1;
inline int EvaluationResponse::_internal_policy_size() const {
  return _internal_policy().size();
}
inline int EvaluationResponse::policy_size() const {
  return _internal_policy_size();
}
inline void EvaluationResponse::clear_policy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.policy_.Clear();
}
inline float EvaluationResponse::policy(int index) const {
  // @@protoc_insertion_point(field_get:EvaluationResponse.policy)
  return _internal_policy().Get(index);
}
inline void EvaluationResponse::set_policy(int index, float value) {
  _internal_mutable_policy()->Set(index, value);
  // @@protoc_insertion_point(field_set:EvaluationResponse.policy)
}
inline void EvaluationResponse::add_policy(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_policy()->Add(value);
  // @@protoc_insertion_point(field_add:EvaluationResponse.policy)
}
inline const ::google::protobuf::RepeatedField<float>& EvaluationResponse::policy() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:EvaluationResponse.policy)
  return _internal_policy();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL EvaluationResponse::mutable_policy()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:EvaluationResponse.policy)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_policy();
}
inline const ::google::protobuf::RepeatedField<float>&
EvaluationResponse::_internal_policy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.policy_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
EvaluationResponse::_internal_mutable_policy() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.policy_;
}

// float value = 2;
inline void EvaluationResponse::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float EvaluationResponse::value() const {
  // @@protoc_insertion_point(field_get:EvaluationResponse.value)
  return _internal_value();
}
inline void EvaluationResponse::set_value(float value) {
  _internal_set_value(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:EvaluationResponse.value)
}
inline float EvaluationResponse::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_;
}
inline void EvaluationResponse::_internal_set_value(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // evaluator_2eproto_2epb_2eh
