// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: evaluator.proto

#include "evaluator.pb.h"
#include "evaluator.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* Evaluator_method_names[] = {
  "/Evaluator/Evaluate",
};

std::unique_ptr< Evaluator::Stub> Evaluator::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Evaluator::Stub> stub(new Evaluator::Stub(channel, options));
  return stub;
}

Evaluator::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Evaluate_(Evaluator_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Evaluator::Stub::Evaluate(::grpc::ClientContext* context, const ::PositionRequest& request, ::EvaluationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::PositionRequest, ::EvaluationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Evaluate_, context, request, response);
}

void Evaluator::Stub::async::Evaluate(::grpc::ClientContext* context, const ::PositionRequest* request, ::EvaluationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::PositionRequest, ::EvaluationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Evaluate_, context, request, response, std::move(f));
}

void Evaluator::Stub::async::Evaluate(::grpc::ClientContext* context, const ::PositionRequest* request, ::EvaluationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Evaluate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::EvaluationResponse>* Evaluator::Stub::PrepareAsyncEvaluateRaw(::grpc::ClientContext* context, const ::PositionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::EvaluationResponse, ::PositionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Evaluate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::EvaluationResponse>* Evaluator::Stub::AsyncEvaluateRaw(::grpc::ClientContext* context, const ::PositionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEvaluateRaw(context, request, cq);
  result->StartCall();
  return result;
}

Evaluator::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Evaluator_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Evaluator::Service, ::PositionRequest, ::EvaluationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Evaluator::Service* service,
             ::grpc::ServerContext* ctx,
             const ::PositionRequest* req,
             ::EvaluationResponse* resp) {
               return service->Evaluate(ctx, req, resp);
             }, this)));
}

Evaluator::Service::~Service() {
}

::grpc::Status Evaluator::Service::Evaluate(::grpc::ServerContext* context, const ::PositionRequest* request, ::EvaluationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


