// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inference.proto

#ifndef PROTOBUF_INCLUDED_inference_2eproto
#define PROTOBUF_INCLUDED_inference_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_inference_2eproto 

namespace protobuf_inference_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_inference_2eproto
namespace inference {
class BatchInferenceRequest;
class BatchInferenceRequestDefaultTypeInternal;
extern BatchInferenceRequestDefaultTypeInternal _BatchInferenceRequest_default_instance_;
class BatchInferenceResponse;
class BatchInferenceResponseDefaultTypeInternal;
extern BatchInferenceResponseDefaultTypeInternal _BatchInferenceResponse_default_instance_;
class EvaluationResult;
class EvaluationResultDefaultTypeInternal;
extern EvaluationResultDefaultTypeInternal _EvaluationResult_default_instance_;
class PositionTensor;
class PositionTensorDefaultTypeInternal;
extern PositionTensorDefaultTypeInternal _PositionTensor_default_instance_;
}  // namespace inference
namespace google {
namespace protobuf {
template<> ::inference::BatchInferenceRequest* Arena::CreateMaybeMessage<::inference::BatchInferenceRequest>(Arena*);
template<> ::inference::BatchInferenceResponse* Arena::CreateMaybeMessage<::inference::BatchInferenceResponse>(Arena*);
template<> ::inference::EvaluationResult* Arena::CreateMaybeMessage<::inference::EvaluationResult>(Arena*);
template<> ::inference::PositionTensor* Arena::CreateMaybeMessage<::inference::PositionTensor>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace inference {

// ===================================================================

class PositionTensor : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inference.PositionTensor) */ {
 public:
  PositionTensor();
  virtual ~PositionTensor();

  PositionTensor(const PositionTensor& from);

  inline PositionTensor& operator=(const PositionTensor& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PositionTensor(PositionTensor&& from) noexcept
    : PositionTensor() {
    *this = ::std::move(from);
  }

  inline PositionTensor& operator=(PositionTensor&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PositionTensor& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PositionTensor* internal_default_instance() {
    return reinterpret_cast<const PositionTensor*>(
               &_PositionTensor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PositionTensor* other);
  friend void swap(PositionTensor& a, PositionTensor& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PositionTensor* New() const final {
    return CreateMaybeMessage<PositionTensor>(NULL);
  }

  PositionTensor* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PositionTensor>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PositionTensor& from);
  void MergeFrom(const PositionTensor& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PositionTensor* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float board_state = 1;
  int board_state_size() const;
  void clear_board_state();
  static const int kBoardStateFieldNumber = 1;
  float board_state(int index) const;
  void set_board_state(int index, float value);
  void add_board_state(float value);
  const ::google::protobuf::RepeatedField< float >&
      board_state() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_board_state();

  // @@protoc_insertion_point(class_scope:inference.PositionTensor)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > board_state_;
  mutable int _board_state_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_inference_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BatchInferenceRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inference.BatchInferenceRequest) */ {
 public:
  BatchInferenceRequest();
  virtual ~BatchInferenceRequest();

  BatchInferenceRequest(const BatchInferenceRequest& from);

  inline BatchInferenceRequest& operator=(const BatchInferenceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BatchInferenceRequest(BatchInferenceRequest&& from) noexcept
    : BatchInferenceRequest() {
    *this = ::std::move(from);
  }

  inline BatchInferenceRequest& operator=(BatchInferenceRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BatchInferenceRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BatchInferenceRequest* internal_default_instance() {
    return reinterpret_cast<const BatchInferenceRequest*>(
               &_BatchInferenceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(BatchInferenceRequest* other);
  friend void swap(BatchInferenceRequest& a, BatchInferenceRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BatchInferenceRequest* New() const final {
    return CreateMaybeMessage<BatchInferenceRequest>(NULL);
  }

  BatchInferenceRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BatchInferenceRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BatchInferenceRequest& from);
  void MergeFrom(const BatchInferenceRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BatchInferenceRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .inference.PositionTensor positions = 1;
  int positions_size() const;
  void clear_positions();
  static const int kPositionsFieldNumber = 1;
  ::inference::PositionTensor* mutable_positions(int index);
  ::google::protobuf::RepeatedPtrField< ::inference::PositionTensor >*
      mutable_positions();
  const ::inference::PositionTensor& positions(int index) const;
  ::inference::PositionTensor* add_positions();
  const ::google::protobuf::RepeatedPtrField< ::inference::PositionTensor >&
      positions() const;

  // @@protoc_insertion_point(class_scope:inference.BatchInferenceRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::inference::PositionTensor > positions_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_inference_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class EvaluationResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inference.EvaluationResult) */ {
 public:
  EvaluationResult();
  virtual ~EvaluationResult();

  EvaluationResult(const EvaluationResult& from);

  inline EvaluationResult& operator=(const EvaluationResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  EvaluationResult(EvaluationResult&& from) noexcept
    : EvaluationResult() {
    *this = ::std::move(from);
  }

  inline EvaluationResult& operator=(EvaluationResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const EvaluationResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EvaluationResult* internal_default_instance() {
    return reinterpret_cast<const EvaluationResult*>(
               &_EvaluationResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(EvaluationResult* other);
  friend void swap(EvaluationResult& a, EvaluationResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EvaluationResult* New() const final {
    return CreateMaybeMessage<EvaluationResult>(NULL);
  }

  EvaluationResult* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<EvaluationResult>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const EvaluationResult& from);
  void MergeFrom(const EvaluationResult& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EvaluationResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float policy_logits = 1;
  int policy_logits_size() const;
  void clear_policy_logits();
  static const int kPolicyLogitsFieldNumber = 1;
  float policy_logits(int index) const;
  void set_policy_logits(int index, float value);
  void add_policy_logits(float value);
  const ::google::protobuf::RepeatedField< float >&
      policy_logits() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_policy_logits();

  // float value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  float value() const;
  void set_value(float value);

  // @@protoc_insertion_point(class_scope:inference.EvaluationResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > policy_logits_;
  mutable int _policy_logits_cached_byte_size_;
  float value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_inference_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BatchInferenceResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:inference.BatchInferenceResponse) */ {
 public:
  BatchInferenceResponse();
  virtual ~BatchInferenceResponse();

  BatchInferenceResponse(const BatchInferenceResponse& from);

  inline BatchInferenceResponse& operator=(const BatchInferenceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BatchInferenceResponse(BatchInferenceResponse&& from) noexcept
    : BatchInferenceResponse() {
    *this = ::std::move(from);
  }

  inline BatchInferenceResponse& operator=(BatchInferenceResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BatchInferenceResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BatchInferenceResponse* internal_default_instance() {
    return reinterpret_cast<const BatchInferenceResponse*>(
               &_BatchInferenceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(BatchInferenceResponse* other);
  friend void swap(BatchInferenceResponse& a, BatchInferenceResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BatchInferenceResponse* New() const final {
    return CreateMaybeMessage<BatchInferenceResponse>(NULL);
  }

  BatchInferenceResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BatchInferenceResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BatchInferenceResponse& from);
  void MergeFrom(const BatchInferenceResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BatchInferenceResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .inference.EvaluationResult evaluations = 1;
  int evaluations_size() const;
  void clear_evaluations();
  static const int kEvaluationsFieldNumber = 1;
  ::inference::EvaluationResult* mutable_evaluations(int index);
  ::google::protobuf::RepeatedPtrField< ::inference::EvaluationResult >*
      mutable_evaluations();
  const ::inference::EvaluationResult& evaluations(int index) const;
  ::inference::EvaluationResult* add_evaluations();
  const ::google::protobuf::RepeatedPtrField< ::inference::EvaluationResult >&
      evaluations() const;

  // @@protoc_insertion_point(class_scope:inference.BatchInferenceResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::inference::EvaluationResult > evaluations_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_inference_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PositionTensor

// repeated float board_state = 1;
inline int PositionTensor::board_state_size() const {
  return board_state_.size();
}
inline void PositionTensor::clear_board_state() {
  board_state_.Clear();
}
inline float PositionTensor::board_state(int index) const {
  // @@protoc_insertion_point(field_get:inference.PositionTensor.board_state)
  return board_state_.Get(index);
}
inline void PositionTensor::set_board_state(int index, float value) {
  board_state_.Set(index, value);
  // @@protoc_insertion_point(field_set:inference.PositionTensor.board_state)
}
inline void PositionTensor::add_board_state(float value) {
  board_state_.Add(value);
  // @@protoc_insertion_point(field_add:inference.PositionTensor.board_state)
}
inline const ::google::protobuf::RepeatedField< float >&
PositionTensor::board_state() const {
  // @@protoc_insertion_point(field_list:inference.PositionTensor.board_state)
  return board_state_;
}
inline ::google::protobuf::RepeatedField< float >*
PositionTensor::mutable_board_state() {
  // @@protoc_insertion_point(field_mutable_list:inference.PositionTensor.board_state)
  return &board_state_;
}

// -------------------------------------------------------------------

// BatchInferenceRequest

// repeated .inference.PositionTensor positions = 1;
inline int BatchInferenceRequest::positions_size() const {
  return positions_.size();
}
inline void BatchInferenceRequest::clear_positions() {
  positions_.Clear();
}
inline ::inference::PositionTensor* BatchInferenceRequest::mutable_positions(int index) {
  // @@protoc_insertion_point(field_mutable:inference.BatchInferenceRequest.positions)
  return positions_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::inference::PositionTensor >*
BatchInferenceRequest::mutable_positions() {
  // @@protoc_insertion_point(field_mutable_list:inference.BatchInferenceRequest.positions)
  return &positions_;
}
inline const ::inference::PositionTensor& BatchInferenceRequest::positions(int index) const {
  // @@protoc_insertion_point(field_get:inference.BatchInferenceRequest.positions)
  return positions_.Get(index);
}
inline ::inference::PositionTensor* BatchInferenceRequest::add_positions() {
  // @@protoc_insertion_point(field_add:inference.BatchInferenceRequest.positions)
  return positions_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::inference::PositionTensor >&
BatchInferenceRequest::positions() const {
  // @@protoc_insertion_point(field_list:inference.BatchInferenceRequest.positions)
  return positions_;
}

// -------------------------------------------------------------------

// EvaluationResult

// repeated float policy_logits = 1;
inline int EvaluationResult::policy_logits_size() const {
  return policy_logits_.size();
}
inline void EvaluationResult::clear_policy_logits() {
  policy_logits_.Clear();
}
inline float EvaluationResult::policy_logits(int index) const {
  // @@protoc_insertion_point(field_get:inference.EvaluationResult.policy_logits)
  return policy_logits_.Get(index);
}
inline void EvaluationResult::set_policy_logits(int index, float value) {
  policy_logits_.Set(index, value);
  // @@protoc_insertion_point(field_set:inference.EvaluationResult.policy_logits)
}
inline void EvaluationResult::add_policy_logits(float value) {
  policy_logits_.Add(value);
  // @@protoc_insertion_point(field_add:inference.EvaluationResult.policy_logits)
}
inline const ::google::protobuf::RepeatedField< float >&
EvaluationResult::policy_logits() const {
  // @@protoc_insertion_point(field_list:inference.EvaluationResult.policy_logits)
  return policy_logits_;
}
inline ::google::protobuf::RepeatedField< float >*
EvaluationResult::mutable_policy_logits() {
  // @@protoc_insertion_point(field_mutable_list:inference.EvaluationResult.policy_logits)
  return &policy_logits_;
}

// float value = 2;
inline void EvaluationResult::clear_value() {
  value_ = 0;
}
inline float EvaluationResult::value() const {
  // @@protoc_insertion_point(field_get:inference.EvaluationResult.value)
  return value_;
}
inline void EvaluationResult::set_value(float value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:inference.EvaluationResult.value)
}

// -------------------------------------------------------------------

// BatchInferenceResponse

// repeated .inference.EvaluationResult evaluations = 1;
inline int BatchInferenceResponse::evaluations_size() const {
  return evaluations_.size();
}
inline void BatchInferenceResponse::clear_evaluations() {
  evaluations_.Clear();
}
inline ::inference::EvaluationResult* BatchInferenceResponse::mutable_evaluations(int index) {
  // @@protoc_insertion_point(field_mutable:inference.BatchInferenceResponse.evaluations)
  return evaluations_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::inference::EvaluationResult >*
BatchInferenceResponse::mutable_evaluations() {
  // @@protoc_insertion_point(field_mutable_list:inference.BatchInferenceResponse.evaluations)
  return &evaluations_;
}
inline const ::inference::EvaluationResult& BatchInferenceResponse::evaluations(int index) const {
  // @@protoc_insertion_point(field_get:inference.BatchInferenceResponse.evaluations)
  return evaluations_.Get(index);
}
inline ::inference::EvaluationResult* BatchInferenceResponse::add_evaluations() {
  // @@protoc_insertion_point(field_add:inference.BatchInferenceResponse.evaluations)
  return evaluations_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::inference::EvaluationResult >&
BatchInferenceResponse::evaluations() const {
  // @@protoc_insertion_point(field_list:inference.BatchInferenceResponse.evaluations)
  return evaluations_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace inference

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_inference_2eproto
