// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inference.proto
// Protobuf C++ Version: 6.31.1

#include "inference.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace inference {

inline constexpr PositionTensor::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : board_state_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PositionTensor::PositionTensor(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PositionTensor_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PositionTensorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PositionTensorDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PositionTensorDefaultTypeInternal() {}
  union {
    PositionTensor _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PositionTensorDefaultTypeInternal _PositionTensor_default_instance_;

inline constexpr Evaluation::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        policy_logits_{},
        value_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Evaluation::Evaluation(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Evaluation_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EvaluationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EvaluationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EvaluationDefaultTypeInternal() {}
  union {
    Evaluation _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EvaluationDefaultTypeInternal _Evaluation_default_instance_;

inline constexpr BatchInferenceResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : evaluations_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BatchInferenceResponse::BatchInferenceResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BatchInferenceResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BatchInferenceResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BatchInferenceResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BatchInferenceResponseDefaultTypeInternal() {}
  union {
    BatchInferenceResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BatchInferenceResponseDefaultTypeInternal _BatchInferenceResponse_default_instance_;

inline constexpr BatchInferenceRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : positions_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BatchInferenceRequest::BatchInferenceRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BatchInferenceRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BatchInferenceRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BatchInferenceRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BatchInferenceRequestDefaultTypeInternal() {}
  union {
    BatchInferenceRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BatchInferenceRequestDefaultTypeInternal _BatchInferenceRequest_default_instance_;
}  // namespace inference
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_inference_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_inference_2eproto = nullptr;
const ::uint32_t
    TableStruct_inference_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::inference::PositionTensor, _impl_.board_state_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::inference::Evaluation, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::inference::Evaluation, _impl_.policy_logits_),
        PROTOBUF_FIELD_OFFSET(::inference::Evaluation, _impl_.value_),
        ~0u,
        0,
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::inference::BatchInferenceRequest, _impl_.positions_),
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::inference::BatchInferenceResponse, _impl_.evaluations_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::inference::PositionTensor)},
        {2, sizeof(::inference::Evaluation)},
        {9, sizeof(::inference::BatchInferenceRequest)},
        {11, sizeof(::inference::BatchInferenceResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::inference::_PositionTensor_default_instance_._instance,
    &::inference::_Evaluation_default_instance_._instance,
    &::inference::_BatchInferenceRequest_default_instance_._instance,
    &::inference::_BatchInferenceResponse_default_instance_._instance,
};
const char descriptor_table_protodef_inference_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017inference.proto\022\tinference\")\n\016Position"
    "Tensor\022\027\n\013board_state\030\001 \003(\002B\002\020\001\"6\n\nEvalu"
    "ation\022\031\n\rpolicy_logits\030\001 \003(\002B\002\020\001\022\r\n\005valu"
    "e\030\002 \001(\002\"E\n\025BatchInferenceRequest\022,\n\tposi"
    "tions\030\001 \003(\0132\031.inference.PositionTensor\"D"
    "\n\026BatchInferenceResponse\022*\n\013evaluations\030"
    "\001 \003(\0132\025.inference.Evaluation2c\n\020Inferenc"
    "eService\022O\n\010Evaluate\022 .inference.BatchIn"
    "ferenceRequest\032!.inference.BatchInferenc"
    "eResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_inference_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_inference_2eproto = {
    false,
    false,
    377,
    descriptor_table_protodef_inference_2eproto,
    "inference.proto",
    &descriptor_table_inference_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_inference_2eproto::offsets,
    file_level_enum_descriptors_inference_2eproto,
    file_level_service_descriptors_inference_2eproto,
};
namespace inference {
// ===================================================================

class PositionTensor::_Internal {
 public:
};

PositionTensor::PositionTensor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PositionTensor_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:inference.PositionTensor)
}
PROTOBUF_NDEBUG_INLINE PositionTensor::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::inference::PositionTensor& from_msg)
      : board_state_{visibility, arena, from.board_state_},
        _cached_size_{0} {}

PositionTensor::PositionTensor(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PositionTensor& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PositionTensor_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PositionTensor* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:inference.PositionTensor)
}
PROTOBUF_NDEBUG_INLINE PositionTensor::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : board_state_{visibility, arena},
        _cached_size_{0} {}

inline void PositionTensor::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PositionTensor::~PositionTensor() {
  // @@protoc_insertion_point(destructor:inference.PositionTensor)
  SharedDtor(*this);
}
inline void PositionTensor::SharedDtor(MessageLite& self) {
  PositionTensor& this_ = static_cast<PositionTensor&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PositionTensor::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PositionTensor(arena);
}
constexpr auto PositionTensor::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PositionTensor, _impl_.board_state_) +
          decltype(PositionTensor::_impl_.board_state_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(PositionTensor), alignof(PositionTensor), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PositionTensor::PlacementNew_,
                                 sizeof(PositionTensor),
                                 alignof(PositionTensor));
  }
}
constexpr auto PositionTensor::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PositionTensor_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PositionTensor::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PositionTensor>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PositionTensor::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PositionTensor>(), &PositionTensor::ByteSizeLong,
              &PositionTensor::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PositionTensor, _impl_._cached_size_),
          false,
      },
      &PositionTensor::kDescriptorMethods,
      &descriptor_table_inference_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PositionTensor_class_data_ =
        PositionTensor::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PositionTensor::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PositionTensor_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PositionTensor_class_data_.tc_table);
  return PositionTensor_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PositionTensor::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PositionTensor_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::inference::PositionTensor>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float board_state = 1 [packed = true];
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PositionTensor, _impl_.board_state_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float board_state = 1 [packed = true];
    {PROTOBUF_FIELD_OFFSET(PositionTensor, _impl_.board_state_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PositionTensor::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.PositionTensor)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.board_state_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PositionTensor::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PositionTensor& this_ = static_cast<const PositionTensor&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PositionTensor::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PositionTensor& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:inference.PositionTensor)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated float board_state = 1 [packed = true];
  if (this_._internal_board_state_size() > 0) {
    target = stream->WriteFixedPacked(1, this_._internal_board_state(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.PositionTensor)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PositionTensor::ByteSizeLong(const MessageLite& base) {
  const PositionTensor& this_ = static_cast<const PositionTensor&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PositionTensor::ByteSizeLong() const {
  const PositionTensor& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:inference.PositionTensor)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated float board_state = 1 [packed = true];
    {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_board_state_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PositionTensor::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PositionTensor*>(&to_msg);
  auto& from = static_cast<const PositionTensor&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:inference.PositionTensor)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_board_state()->MergeFrom(from._internal_board_state());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PositionTensor::CopyFrom(const PositionTensor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.PositionTensor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PositionTensor::InternalSwap(PositionTensor* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.board_state_.InternalSwap(&other->_impl_.board_state_);
}

::google::protobuf::Metadata PositionTensor::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Evaluation::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Evaluation>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Evaluation, _impl_._has_bits_);
};

Evaluation::Evaluation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Evaluation_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:inference.Evaluation)
}
PROTOBUF_NDEBUG_INLINE Evaluation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::inference::Evaluation& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        policy_logits_{visibility, arena, from.policy_logits_} {}

Evaluation::Evaluation(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Evaluation& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Evaluation_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Evaluation* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.value_ = from._impl_.value_;

  // @@protoc_insertion_point(copy_constructor:inference.Evaluation)
}
PROTOBUF_NDEBUG_INLINE Evaluation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        policy_logits_{visibility, arena} {}

inline void Evaluation::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
Evaluation::~Evaluation() {
  // @@protoc_insertion_point(destructor:inference.Evaluation)
  SharedDtor(*this);
}
inline void Evaluation::SharedDtor(MessageLite& self) {
  Evaluation& this_ = static_cast<Evaluation&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Evaluation::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Evaluation(arena);
}
constexpr auto Evaluation::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Evaluation, _impl_.policy_logits_) +
          decltype(Evaluation::_impl_.policy_logits_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Evaluation), alignof(Evaluation), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Evaluation::PlacementNew_,
                                 sizeof(Evaluation),
                                 alignof(Evaluation));
  }
}
constexpr auto Evaluation::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Evaluation_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Evaluation::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Evaluation>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Evaluation::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Evaluation>(), &Evaluation::ByteSizeLong,
              &Evaluation::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Evaluation, _impl_._cached_size_),
          false,
      },
      &Evaluation::kDescriptorMethods,
      &descriptor_table_inference_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Evaluation_class_data_ =
        Evaluation::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Evaluation::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Evaluation_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Evaluation_class_data_.tc_table);
  return Evaluation_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
Evaluation::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Evaluation, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Evaluation_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::inference::Evaluation>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float value = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 0, 0, PROTOBUF_FIELD_OFFSET(Evaluation, _impl_.value_)}},
    // repeated float policy_logits = 1 [packed = true];
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Evaluation, _impl_.policy_logits_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float policy_logits = 1 [packed = true];
    {PROTOBUF_FIELD_OFFSET(Evaluation, _impl_.policy_logits_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // float value = 2;
    {PROTOBUF_FIELD_OFFSET(Evaluation, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Evaluation::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.Evaluation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.policy_logits_.Clear();
  _impl_.value_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Evaluation::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Evaluation& this_ = static_cast<const Evaluation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Evaluation::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Evaluation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:inference.Evaluation)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated float policy_logits = 1 [packed = true];
  if (this_._internal_policy_logits_size() > 0) {
    target = stream->WriteFixedPacked(1, this_._internal_policy_logits(), target);
  }

  // float value = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_value()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_value(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.Evaluation)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Evaluation::ByteSizeLong(const MessageLite& base) {
  const Evaluation& this_ = static_cast<const Evaluation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Evaluation::ByteSizeLong() const {
  const Evaluation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:inference.Evaluation)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated float policy_logits = 1 [packed = true];
    {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_policy_logits_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
   {
    // float value = 2;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_value()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Evaluation::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Evaluation*>(&to_msg);
  auto& from = static_cast<const Evaluation&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:inference.Evaluation)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_policy_logits()->MergeFrom(from._internal_policy_logits());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (::absl::bit_cast<::uint32_t>(from._internal_value()) != 0) {
      _this->_impl_.value_ = from._impl_.value_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Evaluation::CopyFrom(const Evaluation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.Evaluation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Evaluation::InternalSwap(Evaluation* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.policy_logits_.InternalSwap(&other->_impl_.policy_logits_);
  swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata Evaluation::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BatchInferenceRequest::_Internal {
 public:
};

BatchInferenceRequest::BatchInferenceRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BatchInferenceRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:inference.BatchInferenceRequest)
}
PROTOBUF_NDEBUG_INLINE BatchInferenceRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::inference::BatchInferenceRequest& from_msg)
      : positions_{visibility, arena, from.positions_},
        _cached_size_{0} {}

BatchInferenceRequest::BatchInferenceRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BatchInferenceRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BatchInferenceRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BatchInferenceRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:inference.BatchInferenceRequest)
}
PROTOBUF_NDEBUG_INLINE BatchInferenceRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : positions_{visibility, arena},
        _cached_size_{0} {}

inline void BatchInferenceRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BatchInferenceRequest::~BatchInferenceRequest() {
  // @@protoc_insertion_point(destructor:inference.BatchInferenceRequest)
  SharedDtor(*this);
}
inline void BatchInferenceRequest::SharedDtor(MessageLite& self) {
  BatchInferenceRequest& this_ = static_cast<BatchInferenceRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BatchInferenceRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BatchInferenceRequest(arena);
}
constexpr auto BatchInferenceRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BatchInferenceRequest, _impl_.positions_) +
          decltype(BatchInferenceRequest::_impl_.positions_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(BatchInferenceRequest), alignof(BatchInferenceRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BatchInferenceRequest::PlacementNew_,
                                 sizeof(BatchInferenceRequest),
                                 alignof(BatchInferenceRequest));
  }
}
constexpr auto BatchInferenceRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BatchInferenceRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BatchInferenceRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BatchInferenceRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BatchInferenceRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BatchInferenceRequest>(), &BatchInferenceRequest::ByteSizeLong,
              &BatchInferenceRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BatchInferenceRequest, _impl_._cached_size_),
          false,
      },
      &BatchInferenceRequest::kDescriptorMethods,
      &descriptor_table_inference_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BatchInferenceRequest_class_data_ =
        BatchInferenceRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BatchInferenceRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BatchInferenceRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BatchInferenceRequest_class_data_.tc_table);
  return BatchInferenceRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
BatchInferenceRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BatchInferenceRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::inference::BatchInferenceRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .inference.PositionTensor positions = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BatchInferenceRequest, _impl_.positions_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .inference.PositionTensor positions = 1;
    {PROTOBUF_FIELD_OFFSET(BatchInferenceRequest, _impl_.positions_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::inference::PositionTensor>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void BatchInferenceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.BatchInferenceRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.positions_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BatchInferenceRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BatchInferenceRequest& this_ = static_cast<const BatchInferenceRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BatchInferenceRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BatchInferenceRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:inference.BatchInferenceRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .inference.PositionTensor positions = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_positions_size());
       i < n; i++) {
    const auto& repfield = this_._internal_positions().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.BatchInferenceRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BatchInferenceRequest::ByteSizeLong(const MessageLite& base) {
  const BatchInferenceRequest& this_ = static_cast<const BatchInferenceRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BatchInferenceRequest::ByteSizeLong() const {
  const BatchInferenceRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:inference.BatchInferenceRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .inference.PositionTensor positions = 1;
    {
      total_size += 1UL * this_._internal_positions_size();
      for (const auto& msg : this_._internal_positions()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BatchInferenceRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BatchInferenceRequest*>(&to_msg);
  auto& from = static_cast<const BatchInferenceRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:inference.BatchInferenceRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_positions()->MergeFrom(
      from._internal_positions());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BatchInferenceRequest::CopyFrom(const BatchInferenceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.BatchInferenceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BatchInferenceRequest::InternalSwap(BatchInferenceRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.positions_.InternalSwap(&other->_impl_.positions_);
}

::google::protobuf::Metadata BatchInferenceRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BatchInferenceResponse::_Internal {
 public:
};

BatchInferenceResponse::BatchInferenceResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BatchInferenceResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:inference.BatchInferenceResponse)
}
PROTOBUF_NDEBUG_INLINE BatchInferenceResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::inference::BatchInferenceResponse& from_msg)
      : evaluations_{visibility, arena, from.evaluations_},
        _cached_size_{0} {}

BatchInferenceResponse::BatchInferenceResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BatchInferenceResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BatchInferenceResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BatchInferenceResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:inference.BatchInferenceResponse)
}
PROTOBUF_NDEBUG_INLINE BatchInferenceResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : evaluations_{visibility, arena},
        _cached_size_{0} {}

inline void BatchInferenceResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BatchInferenceResponse::~BatchInferenceResponse() {
  // @@protoc_insertion_point(destructor:inference.BatchInferenceResponse)
  SharedDtor(*this);
}
inline void BatchInferenceResponse::SharedDtor(MessageLite& self) {
  BatchInferenceResponse& this_ = static_cast<BatchInferenceResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BatchInferenceResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BatchInferenceResponse(arena);
}
constexpr auto BatchInferenceResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BatchInferenceResponse, _impl_.evaluations_) +
          decltype(BatchInferenceResponse::_impl_.evaluations_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(BatchInferenceResponse), alignof(BatchInferenceResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BatchInferenceResponse::PlacementNew_,
                                 sizeof(BatchInferenceResponse),
                                 alignof(BatchInferenceResponse));
  }
}
constexpr auto BatchInferenceResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BatchInferenceResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BatchInferenceResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BatchInferenceResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BatchInferenceResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BatchInferenceResponse>(), &BatchInferenceResponse::ByteSizeLong,
              &BatchInferenceResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BatchInferenceResponse, _impl_._cached_size_),
          false,
      },
      &BatchInferenceResponse::kDescriptorMethods,
      &descriptor_table_inference_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BatchInferenceResponse_class_data_ =
        BatchInferenceResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BatchInferenceResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BatchInferenceResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BatchInferenceResponse_class_data_.tc_table);
  return BatchInferenceResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
BatchInferenceResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BatchInferenceResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::inference::BatchInferenceResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .inference.Evaluation evaluations = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BatchInferenceResponse, _impl_.evaluations_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .inference.Evaluation evaluations = 1;
    {PROTOBUF_FIELD_OFFSET(BatchInferenceResponse, _impl_.evaluations_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::inference::Evaluation>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void BatchInferenceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.BatchInferenceResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.evaluations_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BatchInferenceResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BatchInferenceResponse& this_ = static_cast<const BatchInferenceResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BatchInferenceResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BatchInferenceResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:inference.BatchInferenceResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .inference.Evaluation evaluations = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_evaluations_size());
       i < n; i++) {
    const auto& repfield = this_._internal_evaluations().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.BatchInferenceResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BatchInferenceResponse::ByteSizeLong(const MessageLite& base) {
  const BatchInferenceResponse& this_ = static_cast<const BatchInferenceResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BatchInferenceResponse::ByteSizeLong() const {
  const BatchInferenceResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:inference.BatchInferenceResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .inference.Evaluation evaluations = 1;
    {
      total_size += 1UL * this_._internal_evaluations_size();
      for (const auto& msg : this_._internal_evaluations()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BatchInferenceResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BatchInferenceResponse*>(&to_msg);
  auto& from = static_cast<const BatchInferenceResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:inference.BatchInferenceResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_evaluations()->MergeFrom(
      from._internal_evaluations());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BatchInferenceResponse::CopyFrom(const BatchInferenceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.BatchInferenceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BatchInferenceResponse::InternalSwap(BatchInferenceResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.evaluations_.InternalSwap(&other->_impl_.evaluations_);
}

::google::protobuf::Metadata BatchInferenceResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace inference
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_inference_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
