// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto

#include "inference.pb.h"
#include "inference.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace inference {

static const char* InferenceService_method_names[] = {
  "/inference.InferenceService/Evaluate",
};

std::unique_ptr< InferenceService::Stub> InferenceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InferenceService::Stub> stub(new InferenceService::Stub(channel, options));
  return stub;
}

InferenceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Evaluate_(InferenceService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status InferenceService::Stub::Evaluate(::grpc::ClientContext* context, const ::inference::BatchInferenceRequest& request, ::inference::BatchInferenceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::inference::BatchInferenceRequest, ::inference::BatchInferenceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Evaluate_, context, request, response);
}

void InferenceService::Stub::async::Evaluate(::grpc::ClientContext* context, const ::inference::BatchInferenceRequest* request, ::inference::BatchInferenceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::inference::BatchInferenceRequest, ::inference::BatchInferenceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Evaluate_, context, request, response, std::move(f));
}

void InferenceService::Stub::async::Evaluate(::grpc::ClientContext* context, const ::inference::BatchInferenceRequest* request, ::inference::BatchInferenceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Evaluate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::inference::BatchInferenceResponse>* InferenceService::Stub::PrepareAsyncEvaluateRaw(::grpc::ClientContext* context, const ::inference::BatchInferenceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::inference::BatchInferenceResponse, ::inference::BatchInferenceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Evaluate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::inference::BatchInferenceResponse>* InferenceService::Stub::AsyncEvaluateRaw(::grpc::ClientContext* context, const ::inference::BatchInferenceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEvaluateRaw(context, request, cq);
  result->StartCall();
  return result;
}

InferenceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InferenceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InferenceService::Service, ::inference::BatchInferenceRequest, ::inference::BatchInferenceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InferenceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::inference::BatchInferenceRequest* req,
             ::inference::BatchInferenceResponse* resp) {
               return service->Evaluate(ctx, req, resp);
             }, this)));
}

InferenceService::Service::~Service() {
}

::grpc::Status InferenceService::Service::Evaluate(::grpc::ServerContext* context, const ::inference::BatchInferenceRequest* request, ::inference::BatchInferenceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace inference

