// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inference.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_inference_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_inference_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_inference_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_inference_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_inference_2eproto;
namespace inference {
class BatchInferenceRequest;
struct BatchInferenceRequestDefaultTypeInternal;
extern BatchInferenceRequestDefaultTypeInternal _BatchInferenceRequest_default_instance_;
class BatchInferenceResponse;
struct BatchInferenceResponseDefaultTypeInternal;
extern BatchInferenceResponseDefaultTypeInternal _BatchInferenceResponse_default_instance_;
class EvaluationResult;
struct EvaluationResultDefaultTypeInternal;
extern EvaluationResultDefaultTypeInternal _EvaluationResult_default_instance_;
class PositionTensor;
struct PositionTensorDefaultTypeInternal;
extern PositionTensorDefaultTypeInternal _PositionTensor_default_instance_;
}  // namespace inference
PROTOBUF_NAMESPACE_OPEN
template<> ::inference::BatchInferenceRequest* Arena::CreateMaybeMessage<::inference::BatchInferenceRequest>(Arena*);
template<> ::inference::BatchInferenceResponse* Arena::CreateMaybeMessage<::inference::BatchInferenceResponse>(Arena*);
template<> ::inference::EvaluationResult* Arena::CreateMaybeMessage<::inference::EvaluationResult>(Arena*);
template<> ::inference::PositionTensor* Arena::CreateMaybeMessage<::inference::PositionTensor>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace inference {

// ===================================================================

class PositionTensor final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:inference.PositionTensor) */ {
 public:
  inline PositionTensor() : PositionTensor(nullptr) {}
  ~PositionTensor() override;
  explicit PROTOBUF_CONSTEXPR PositionTensor(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PositionTensor(const PositionTensor& from);
  PositionTensor(PositionTensor&& from) noexcept
    : PositionTensor() {
    *this = ::std::move(from);
  }

  inline PositionTensor& operator=(const PositionTensor& from) {
    CopyFrom(from);
    return *this;
  }
  inline PositionTensor& operator=(PositionTensor&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PositionTensor& default_instance() {
    return *internal_default_instance();
  }
  static inline const PositionTensor* internal_default_instance() {
    return reinterpret_cast<const PositionTensor*>(
               &_PositionTensor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PositionTensor& a, PositionTensor& b) {
    a.Swap(&b);
  }
  inline void Swap(PositionTensor* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PositionTensor* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PositionTensor* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PositionTensor>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PositionTensor& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PositionTensor& from) {
    PositionTensor::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PositionTensor* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "inference.PositionTensor";
  }
  protected:
  explicit PositionTensor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBoardStateFieldNumber = 1,
  };
  // repeated float board_state = 1;
  int board_state_size() const;
  private:
  int _internal_board_state_size() const;
  public:
  void clear_board_state();
  private:
  float _internal_board_state(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_board_state() const;
  void _internal_add_board_state(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_board_state();
  public:
  float board_state(int index) const;
  void set_board_state(int index, float value);
  void add_board_state(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      board_state() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_board_state();

  // @@protoc_insertion_point(class_scope:inference.PositionTensor)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > board_state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};
// -------------------------------------------------------------------

class BatchInferenceRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:inference.BatchInferenceRequest) */ {
 public:
  inline BatchInferenceRequest() : BatchInferenceRequest(nullptr) {}
  ~BatchInferenceRequest() override;
  explicit PROTOBUF_CONSTEXPR BatchInferenceRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BatchInferenceRequest(const BatchInferenceRequest& from);
  BatchInferenceRequest(BatchInferenceRequest&& from) noexcept
    : BatchInferenceRequest() {
    *this = ::std::move(from);
  }

  inline BatchInferenceRequest& operator=(const BatchInferenceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BatchInferenceRequest& operator=(BatchInferenceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BatchInferenceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BatchInferenceRequest* internal_default_instance() {
    return reinterpret_cast<const BatchInferenceRequest*>(
               &_BatchInferenceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BatchInferenceRequest& a, BatchInferenceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(BatchInferenceRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BatchInferenceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BatchInferenceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BatchInferenceRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BatchInferenceRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BatchInferenceRequest& from) {
    BatchInferenceRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BatchInferenceRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "inference.BatchInferenceRequest";
  }
  protected:
  explicit BatchInferenceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionsFieldNumber = 1,
  };
  // repeated .inference.PositionTensor positions = 1;
  int positions_size() const;
  private:
  int _internal_positions_size() const;
  public:
  void clear_positions();
  ::inference::PositionTensor* mutable_positions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::inference::PositionTensor >*
      mutable_positions();
  private:
  const ::inference::PositionTensor& _internal_positions(int index) const;
  ::inference::PositionTensor* _internal_add_positions();
  public:
  const ::inference::PositionTensor& positions(int index) const;
  ::inference::PositionTensor* add_positions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::inference::PositionTensor >&
      positions() const;

  // @@protoc_insertion_point(class_scope:inference.BatchInferenceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::inference::PositionTensor > positions_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};
// -------------------------------------------------------------------

class EvaluationResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:inference.EvaluationResult) */ {
 public:
  inline EvaluationResult() : EvaluationResult(nullptr) {}
  ~EvaluationResult() override;
  explicit PROTOBUF_CONSTEXPR EvaluationResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EvaluationResult(const EvaluationResult& from);
  EvaluationResult(EvaluationResult&& from) noexcept
    : EvaluationResult() {
    *this = ::std::move(from);
  }

  inline EvaluationResult& operator=(const EvaluationResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline EvaluationResult& operator=(EvaluationResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EvaluationResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const EvaluationResult* internal_default_instance() {
    return reinterpret_cast<const EvaluationResult*>(
               &_EvaluationResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(EvaluationResult& a, EvaluationResult& b) {
    a.Swap(&b);
  }
  inline void Swap(EvaluationResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EvaluationResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EvaluationResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EvaluationResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EvaluationResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EvaluationResult& from) {
    EvaluationResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EvaluationResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "inference.EvaluationResult";
  }
  protected:
  explicit EvaluationResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPolicyLogitsFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // repeated float policy_logits = 1;
  int policy_logits_size() const;
  private:
  int _internal_policy_logits_size() const;
  public:
  void clear_policy_logits();
  private:
  float _internal_policy_logits(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_policy_logits() const;
  void _internal_add_policy_logits(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_policy_logits();
  public:
  float policy_logits(int index) const;
  void set_policy_logits(int index, float value);
  void add_policy_logits(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      policy_logits() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_policy_logits();

  // float value = 2;
  void clear_value();
  float value() const;
  void set_value(float value);
  private:
  float _internal_value() const;
  void _internal_set_value(float value);
  public:

  // @@protoc_insertion_point(class_scope:inference.EvaluationResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > policy_logits_;
    float value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};
// -------------------------------------------------------------------

class BatchInferenceResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:inference.BatchInferenceResponse) */ {
 public:
  inline BatchInferenceResponse() : BatchInferenceResponse(nullptr) {}
  ~BatchInferenceResponse() override;
  explicit PROTOBUF_CONSTEXPR BatchInferenceResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BatchInferenceResponse(const BatchInferenceResponse& from);
  BatchInferenceResponse(BatchInferenceResponse&& from) noexcept
    : BatchInferenceResponse() {
    *this = ::std::move(from);
  }

  inline BatchInferenceResponse& operator=(const BatchInferenceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BatchInferenceResponse& operator=(BatchInferenceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BatchInferenceResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BatchInferenceResponse* internal_default_instance() {
    return reinterpret_cast<const BatchInferenceResponse*>(
               &_BatchInferenceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BatchInferenceResponse& a, BatchInferenceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BatchInferenceResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BatchInferenceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BatchInferenceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BatchInferenceResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BatchInferenceResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BatchInferenceResponse& from) {
    BatchInferenceResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BatchInferenceResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "inference.BatchInferenceResponse";
  }
  protected:
  explicit BatchInferenceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEvaluationsFieldNumber = 1,
  };
  // repeated .inference.EvaluationResult evaluations = 1;
  int evaluations_size() const;
  private:
  int _internal_evaluations_size() const;
  public:
  void clear_evaluations();
  ::inference::EvaluationResult* mutable_evaluations(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::inference::EvaluationResult >*
      mutable_evaluations();
  private:
  const ::inference::EvaluationResult& _internal_evaluations(int index) const;
  ::inference::EvaluationResult* _internal_add_evaluations();
  public:
  const ::inference::EvaluationResult& evaluations(int index) const;
  ::inference::EvaluationResult* add_evaluations();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::inference::EvaluationResult >&
      evaluations() const;

  // @@protoc_insertion_point(class_scope:inference.BatchInferenceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::inference::EvaluationResult > evaluations_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PositionTensor

// repeated float board_state = 1;
inline int PositionTensor::_internal_board_state_size() const {
  return _impl_.board_state_.size();
}
inline int PositionTensor::board_state_size() const {
  return _internal_board_state_size();
}
inline void PositionTensor::clear_board_state() {
  _impl_.board_state_.Clear();
}
inline float PositionTensor::_internal_board_state(int index) const {
  return _impl_.board_state_.Get(index);
}
inline float PositionTensor::board_state(int index) const {
  // @@protoc_insertion_point(field_get:inference.PositionTensor.board_state)
  return _internal_board_state(index);
}
inline void PositionTensor::set_board_state(int index, float value) {
  _impl_.board_state_.Set(index, value);
  // @@protoc_insertion_point(field_set:inference.PositionTensor.board_state)
}
inline void PositionTensor::_internal_add_board_state(float value) {
  _impl_.board_state_.Add(value);
}
inline void PositionTensor::add_board_state(float value) {
  _internal_add_board_state(value);
  // @@protoc_insertion_point(field_add:inference.PositionTensor.board_state)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PositionTensor::_internal_board_state() const {
  return _impl_.board_state_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
PositionTensor::board_state() const {
  // @@protoc_insertion_point(field_list:inference.PositionTensor.board_state)
  return _internal_board_state();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PositionTensor::_internal_mutable_board_state() {
  return &_impl_.board_state_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
PositionTensor::mutable_board_state() {
  // @@protoc_insertion_point(field_mutable_list:inference.PositionTensor.board_state)
  return _internal_mutable_board_state();
}

// -------------------------------------------------------------------

// BatchInferenceRequest

// repeated .inference.PositionTensor positions = 1;
inline int BatchInferenceRequest::_internal_positions_size() const {
  return _impl_.positions_.size();
}
inline int BatchInferenceRequest::positions_size() const {
  return _internal_positions_size();
}
inline void BatchInferenceRequest::clear_positions() {
  _impl_.positions_.Clear();
}
inline ::inference::PositionTensor* BatchInferenceRequest::mutable_positions(int index) {
  // @@protoc_insertion_point(field_mutable:inference.BatchInferenceRequest.positions)
  return _impl_.positions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::inference::PositionTensor >*
BatchInferenceRequest::mutable_positions() {
  // @@protoc_insertion_point(field_mutable_list:inference.BatchInferenceRequest.positions)
  return &_impl_.positions_;
}
inline const ::inference::PositionTensor& BatchInferenceRequest::_internal_positions(int index) const {
  return _impl_.positions_.Get(index);
}
inline const ::inference::PositionTensor& BatchInferenceRequest::positions(int index) const {
  // @@protoc_insertion_point(field_get:inference.BatchInferenceRequest.positions)
  return _internal_positions(index);
}
inline ::inference::PositionTensor* BatchInferenceRequest::_internal_add_positions() {
  return _impl_.positions_.Add();
}
inline ::inference::PositionTensor* BatchInferenceRequest::add_positions() {
  ::inference::PositionTensor* _add = _internal_add_positions();
  // @@protoc_insertion_point(field_add:inference.BatchInferenceRequest.positions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::inference::PositionTensor >&
BatchInferenceRequest::positions() const {
  // @@protoc_insertion_point(field_list:inference.BatchInferenceRequest.positions)
  return _impl_.positions_;
}

// -------------------------------------------------------------------

// EvaluationResult

// repeated float policy_logits = 1;
inline int EvaluationResult::_internal_policy_logits_size() const {
  return _impl_.policy_logits_.size();
}
inline int EvaluationResult::policy_logits_size() const {
  return _internal_policy_logits_size();
}
inline void EvaluationResult::clear_policy_logits() {
  _impl_.policy_logits_.Clear();
}
inline float EvaluationResult::_internal_policy_logits(int index) const {
  return _impl_.policy_logits_.Get(index);
}
inline float EvaluationResult::policy_logits(int index) const {
  // @@protoc_insertion_point(field_get:inference.EvaluationResult.policy_logits)
  return _internal_policy_logits(index);
}
inline void EvaluationResult::set_policy_logits(int index, float value) {
  _impl_.policy_logits_.Set(index, value);
  // @@protoc_insertion_point(field_set:inference.EvaluationResult.policy_logits)
}
inline void EvaluationResult::_internal_add_policy_logits(float value) {
  _impl_.policy_logits_.Add(value);
}
inline void EvaluationResult::add_policy_logits(float value) {
  _internal_add_policy_logits(value);
  // @@protoc_insertion_point(field_add:inference.EvaluationResult.policy_logits)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
EvaluationResult::_internal_policy_logits() const {
  return _impl_.policy_logits_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
EvaluationResult::policy_logits() const {
  // @@protoc_insertion_point(field_list:inference.EvaluationResult.policy_logits)
  return _internal_policy_logits();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
EvaluationResult::_internal_mutable_policy_logits() {
  return &_impl_.policy_logits_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
EvaluationResult::mutable_policy_logits() {
  // @@protoc_insertion_point(field_mutable_list:inference.EvaluationResult.policy_logits)
  return _internal_mutable_policy_logits();
}

// float value = 2;
inline void EvaluationResult::clear_value() {
  _impl_.value_ = 0;
}
inline float EvaluationResult::_internal_value() const {
  return _impl_.value_;
}
inline float EvaluationResult::value() const {
  // @@protoc_insertion_point(field_get:inference.EvaluationResult.value)
  return _internal_value();
}
inline void EvaluationResult::_internal_set_value(float value) {
  
  _impl_.value_ = value;
}
inline void EvaluationResult::set_value(float value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:inference.EvaluationResult.value)
}

// -------------------------------------------------------------------

// BatchInferenceResponse

// repeated .inference.EvaluationResult evaluations = 1;
inline int BatchInferenceResponse::_internal_evaluations_size() const {
  return _impl_.evaluations_.size();
}
inline int BatchInferenceResponse::evaluations_size() const {
  return _internal_evaluations_size();
}
inline void BatchInferenceResponse::clear_evaluations() {
  _impl_.evaluations_.Clear();
}
inline ::inference::EvaluationResult* BatchInferenceResponse::mutable_evaluations(int index) {
  // @@protoc_insertion_point(field_mutable:inference.BatchInferenceResponse.evaluations)
  return _impl_.evaluations_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::inference::EvaluationResult >*
BatchInferenceResponse::mutable_evaluations() {
  // @@protoc_insertion_point(field_mutable_list:inference.BatchInferenceResponse.evaluations)
  return &_impl_.evaluations_;
}
inline const ::inference::EvaluationResult& BatchInferenceResponse::_internal_evaluations(int index) const {
  return _impl_.evaluations_.Get(index);
}
inline const ::inference::EvaluationResult& BatchInferenceResponse::evaluations(int index) const {
  // @@protoc_insertion_point(field_get:inference.BatchInferenceResponse.evaluations)
  return _internal_evaluations(index);
}
inline ::inference::EvaluationResult* BatchInferenceResponse::_internal_add_evaluations() {
  return _impl_.evaluations_.Add();
}
inline ::inference::EvaluationResult* BatchInferenceResponse::add_evaluations() {
  ::inference::EvaluationResult* _add = _internal_add_evaluations();
  // @@protoc_insertion_point(field_add:inference.BatchInferenceResponse.evaluations)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::inference::EvaluationResult >&
BatchInferenceResponse::evaluations() const {
  // @@protoc_insertion_point(field_list:inference.BatchInferenceResponse.evaluations)
  return _impl_.evaluations_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace inference

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_inference_2eproto
