// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inference.proto

#include "inference.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_inference_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_inference_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_EvaluationResult;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_inference_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PositionTensor;
}  // namespace protobuf_inference_2eproto
namespace inference {
class PositionTensorDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PositionTensor>
      _instance;
} _PositionTensor_default_instance_;
class BatchInferenceRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BatchInferenceRequest>
      _instance;
} _BatchInferenceRequest_default_instance_;
class EvaluationResultDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<EvaluationResult>
      _instance;
} _EvaluationResult_default_instance_;
class BatchInferenceResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BatchInferenceResponse>
      _instance;
} _BatchInferenceResponse_default_instance_;
}  // namespace inference
namespace protobuf_inference_2eproto {
static void InitDefaultsPositionTensor() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::inference::_PositionTensor_default_instance_;
    new (ptr) ::inference::PositionTensor();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::inference::PositionTensor::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PositionTensor =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPositionTensor}, {}};

static void InitDefaultsBatchInferenceRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::inference::_BatchInferenceRequest_default_instance_;
    new (ptr) ::inference::BatchInferenceRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::inference::BatchInferenceRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_BatchInferenceRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsBatchInferenceRequest}, {
      &protobuf_inference_2eproto::scc_info_PositionTensor.base,}};

static void InitDefaultsEvaluationResult() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::inference::_EvaluationResult_default_instance_;
    new (ptr) ::inference::EvaluationResult();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::inference::EvaluationResult::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_EvaluationResult =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsEvaluationResult}, {}};

static void InitDefaultsBatchInferenceResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::inference::_BatchInferenceResponse_default_instance_;
    new (ptr) ::inference::BatchInferenceResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::inference::BatchInferenceResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_BatchInferenceResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsBatchInferenceResponse}, {
      &protobuf_inference_2eproto::scc_info_EvaluationResult.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_PositionTensor.base);
  ::google::protobuf::internal::InitSCC(&scc_info_BatchInferenceRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_EvaluationResult.base);
  ::google::protobuf::internal::InitSCC(&scc_info_BatchInferenceResponse.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::PositionTensor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::PositionTensor, board_state_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::BatchInferenceRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::BatchInferenceRequest, positions_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::EvaluationResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::EvaluationResult, policy_logits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::EvaluationResult, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::BatchInferenceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::BatchInferenceResponse, evaluations_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::inference::PositionTensor)},
  { 6, -1, sizeof(::inference::BatchInferenceRequest)},
  { 12, -1, sizeof(::inference::EvaluationResult)},
  { 19, -1, sizeof(::inference::BatchInferenceResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::inference::_PositionTensor_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::inference::_BatchInferenceRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::inference::_EvaluationResult_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::inference::_BatchInferenceResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "inference.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017inference.proto\022\tinference\"%\n\016Position"
      "Tensor\022\023\n\013board_state\030\001 \003(\002\"E\n\025BatchInfe"
      "renceRequest\022,\n\tpositions\030\001 \003(\0132\031.infere"
      "nce.PositionTensor\"8\n\020EvaluationResult\022\025"
      "\n\rpolicy_logits\030\001 \003(\002\022\r\n\005value\030\002 \001(\002\"J\n\026"
      "BatchInferenceResponse\0220\n\013evaluations\030\001 "
      "\003(\0132\033.inference.EvaluationResult2c\n\020Infe"
      "renceService\022O\n\010Evaluate\022 .inference.Bat"
      "chInferenceRequest\032!.inference.BatchInfe"
      "renceResponseb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 381);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "inference.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_inference_2eproto
namespace inference {

// ===================================================================

void PositionTensor::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PositionTensor::kBoardStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PositionTensor::PositionTensor()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_inference_2eproto::scc_info_PositionTensor.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:inference.PositionTensor)
}
PositionTensor::PositionTensor(const PositionTensor& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      board_state_(from.board_state_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:inference.PositionTensor)
}

void PositionTensor::SharedCtor() {
}

PositionTensor::~PositionTensor() {
  // @@protoc_insertion_point(destructor:inference.PositionTensor)
  SharedDtor();
}

void PositionTensor::SharedDtor() {
}

void PositionTensor::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PositionTensor::descriptor() {
  ::protobuf_inference_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_inference_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PositionTensor& PositionTensor::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_inference_2eproto::scc_info_PositionTensor.base);
  return *internal_default_instance();
}


void PositionTensor::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.PositionTensor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  board_state_.Clear();
  _internal_metadata_.Clear();
}

bool PositionTensor::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:inference.PositionTensor)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float board_state = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_board_state())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 10u, input, this->mutable_board_state())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:inference.PositionTensor)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:inference.PositionTensor)
  return false;
#undef DO_
}

void PositionTensor::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:inference.PositionTensor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float board_state = 1;
  if (this->board_state_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _board_state_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->board_state().data(), this->board_state_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:inference.PositionTensor)
}

::google::protobuf::uint8* PositionTensor::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:inference.PositionTensor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float board_state = 1;
  if (this->board_state_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _board_state_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->board_state_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.PositionTensor)
  return target;
}

size_t PositionTensor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.PositionTensor)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float board_state = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->board_state_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _board_state_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PositionTensor::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:inference.PositionTensor)
  GOOGLE_DCHECK_NE(&from, this);
  const PositionTensor* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PositionTensor>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:inference.PositionTensor)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:inference.PositionTensor)
    MergeFrom(*source);
  }
}

void PositionTensor::MergeFrom(const PositionTensor& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inference.PositionTensor)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  board_state_.MergeFrom(from.board_state_);
}

void PositionTensor::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:inference.PositionTensor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PositionTensor::CopyFrom(const PositionTensor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.PositionTensor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PositionTensor::IsInitialized() const {
  return true;
}

void PositionTensor::Swap(PositionTensor* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PositionTensor::InternalSwap(PositionTensor* other) {
  using std::swap;
  board_state_.InternalSwap(&other->board_state_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PositionTensor::GetMetadata() const {
  protobuf_inference_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_inference_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void BatchInferenceRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BatchInferenceRequest::kPositionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BatchInferenceRequest::BatchInferenceRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_inference_2eproto::scc_info_BatchInferenceRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:inference.BatchInferenceRequest)
}
BatchInferenceRequest::BatchInferenceRequest(const BatchInferenceRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      positions_(from.positions_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:inference.BatchInferenceRequest)
}

void BatchInferenceRequest::SharedCtor() {
}

BatchInferenceRequest::~BatchInferenceRequest() {
  // @@protoc_insertion_point(destructor:inference.BatchInferenceRequest)
  SharedDtor();
}

void BatchInferenceRequest::SharedDtor() {
}

void BatchInferenceRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BatchInferenceRequest::descriptor() {
  ::protobuf_inference_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_inference_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BatchInferenceRequest& BatchInferenceRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_inference_2eproto::scc_info_BatchInferenceRequest.base);
  return *internal_default_instance();
}


void BatchInferenceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.BatchInferenceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  positions_.Clear();
  _internal_metadata_.Clear();
}

bool BatchInferenceRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:inference.BatchInferenceRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .inference.PositionTensor positions = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_positions()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:inference.BatchInferenceRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:inference.BatchInferenceRequest)
  return false;
#undef DO_
}

void BatchInferenceRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:inference.BatchInferenceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .inference.PositionTensor positions = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->positions_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->positions(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:inference.BatchInferenceRequest)
}

::google::protobuf::uint8* BatchInferenceRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:inference.BatchInferenceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .inference.PositionTensor positions = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->positions_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->positions(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.BatchInferenceRequest)
  return target;
}

size_t BatchInferenceRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.BatchInferenceRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .inference.PositionTensor positions = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->positions_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->positions(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BatchInferenceRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:inference.BatchInferenceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const BatchInferenceRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BatchInferenceRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:inference.BatchInferenceRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:inference.BatchInferenceRequest)
    MergeFrom(*source);
  }
}

void BatchInferenceRequest::MergeFrom(const BatchInferenceRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inference.BatchInferenceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  positions_.MergeFrom(from.positions_);
}

void BatchInferenceRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:inference.BatchInferenceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BatchInferenceRequest::CopyFrom(const BatchInferenceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.BatchInferenceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BatchInferenceRequest::IsInitialized() const {
  return true;
}

void BatchInferenceRequest::Swap(BatchInferenceRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BatchInferenceRequest::InternalSwap(BatchInferenceRequest* other) {
  using std::swap;
  CastToBase(&positions_)->InternalSwap(CastToBase(&other->positions_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BatchInferenceRequest::GetMetadata() const {
  protobuf_inference_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_inference_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void EvaluationResult::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EvaluationResult::kPolicyLogitsFieldNumber;
const int EvaluationResult::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EvaluationResult::EvaluationResult()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_inference_2eproto::scc_info_EvaluationResult.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:inference.EvaluationResult)
}
EvaluationResult::EvaluationResult(const EvaluationResult& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      policy_logits_(from.policy_logits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:inference.EvaluationResult)
}

void EvaluationResult::SharedCtor() {
  value_ = 0;
}

EvaluationResult::~EvaluationResult() {
  // @@protoc_insertion_point(destructor:inference.EvaluationResult)
  SharedDtor();
}

void EvaluationResult::SharedDtor() {
}

void EvaluationResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* EvaluationResult::descriptor() {
  ::protobuf_inference_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_inference_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const EvaluationResult& EvaluationResult::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_inference_2eproto::scc_info_EvaluationResult.base);
  return *internal_default_instance();
}


void EvaluationResult::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.EvaluationResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  policy_logits_.Clear();
  value_ = 0;
  _internal_metadata_.Clear();
}

bool EvaluationResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:inference.EvaluationResult)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float policy_logits = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_policy_logits())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 10u, input, this->mutable_policy_logits())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:inference.EvaluationResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:inference.EvaluationResult)
  return false;
#undef DO_
}

void EvaluationResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:inference.EvaluationResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float policy_logits = 1;
  if (this->policy_logits_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _policy_logits_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->policy_logits().data(), this->policy_logits_size(), output);
  }

  // float value = 2;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:inference.EvaluationResult)
}

::google::protobuf::uint8* EvaluationResult::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:inference.EvaluationResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float policy_logits = 1;
  if (this->policy_logits_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _policy_logits_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->policy_logits_, target);
  }

  // float value = 2;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.EvaluationResult)
  return target;
}

size_t EvaluationResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.EvaluationResult)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float policy_logits = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->policy_logits_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _policy_logits_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // float value = 2;
  if (this->value() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EvaluationResult::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:inference.EvaluationResult)
  GOOGLE_DCHECK_NE(&from, this);
  const EvaluationResult* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EvaluationResult>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:inference.EvaluationResult)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:inference.EvaluationResult)
    MergeFrom(*source);
  }
}

void EvaluationResult::MergeFrom(const EvaluationResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inference.EvaluationResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  policy_logits_.MergeFrom(from.policy_logits_);
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void EvaluationResult::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:inference.EvaluationResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EvaluationResult::CopyFrom(const EvaluationResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.EvaluationResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EvaluationResult::IsInitialized() const {
  return true;
}

void EvaluationResult::Swap(EvaluationResult* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EvaluationResult::InternalSwap(EvaluationResult* other) {
  using std::swap;
  policy_logits_.InternalSwap(&other->policy_logits_);
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata EvaluationResult::GetMetadata() const {
  protobuf_inference_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_inference_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void BatchInferenceResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BatchInferenceResponse::kEvaluationsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BatchInferenceResponse::BatchInferenceResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_inference_2eproto::scc_info_BatchInferenceResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:inference.BatchInferenceResponse)
}
BatchInferenceResponse::BatchInferenceResponse(const BatchInferenceResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      evaluations_(from.evaluations_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:inference.BatchInferenceResponse)
}

void BatchInferenceResponse::SharedCtor() {
}

BatchInferenceResponse::~BatchInferenceResponse() {
  // @@protoc_insertion_point(destructor:inference.BatchInferenceResponse)
  SharedDtor();
}

void BatchInferenceResponse::SharedDtor() {
}

void BatchInferenceResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BatchInferenceResponse::descriptor() {
  ::protobuf_inference_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_inference_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BatchInferenceResponse& BatchInferenceResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_inference_2eproto::scc_info_BatchInferenceResponse.base);
  return *internal_default_instance();
}


void BatchInferenceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.BatchInferenceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  evaluations_.Clear();
  _internal_metadata_.Clear();
}

bool BatchInferenceResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:inference.BatchInferenceResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .inference.EvaluationResult evaluations = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_evaluations()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:inference.BatchInferenceResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:inference.BatchInferenceResponse)
  return false;
#undef DO_
}

void BatchInferenceResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:inference.BatchInferenceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .inference.EvaluationResult evaluations = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->evaluations_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->evaluations(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:inference.BatchInferenceResponse)
}

::google::protobuf::uint8* BatchInferenceResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:inference.BatchInferenceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .inference.EvaluationResult evaluations = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->evaluations_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->evaluations(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.BatchInferenceResponse)
  return target;
}

size_t BatchInferenceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.BatchInferenceResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .inference.EvaluationResult evaluations = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->evaluations_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->evaluations(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BatchInferenceResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:inference.BatchInferenceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const BatchInferenceResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BatchInferenceResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:inference.BatchInferenceResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:inference.BatchInferenceResponse)
    MergeFrom(*source);
  }
}

void BatchInferenceResponse::MergeFrom(const BatchInferenceResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inference.BatchInferenceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  evaluations_.MergeFrom(from.evaluations_);
}

void BatchInferenceResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:inference.BatchInferenceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BatchInferenceResponse::CopyFrom(const BatchInferenceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.BatchInferenceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BatchInferenceResponse::IsInitialized() const {
  return true;
}

void BatchInferenceResponse::Swap(BatchInferenceResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BatchInferenceResponse::InternalSwap(BatchInferenceResponse* other) {
  using std::swap;
  CastToBase(&evaluations_)->InternalSwap(CastToBase(&other->evaluations_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BatchInferenceResponse::GetMetadata() const {
  protobuf_inference_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_inference_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace inference
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::inference::PositionTensor* Arena::CreateMaybeMessage< ::inference::PositionTensor >(Arena* arena) {
  return Arena::CreateInternal< ::inference::PositionTensor >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::inference::BatchInferenceRequest* Arena::CreateMaybeMessage< ::inference::BatchInferenceRequest >(Arena* arena) {
  return Arena::CreateInternal< ::inference::BatchInferenceRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::inference::EvaluationResult* Arena::CreateMaybeMessage< ::inference::EvaluationResult >(Arena* arena) {
  return Arena::CreateInternal< ::inference::EvaluationResult >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::inference::BatchInferenceResponse* Arena::CreateMaybeMessage< ::inference::BatchInferenceResponse >(Arena* arena) {
  return Arena::CreateInternal< ::inference::BatchInferenceResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
