// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto

#include "inference.pb.h"
#include "inference.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace inference {

static const char* InferenceService_method_names[] = {
  "/inference.InferenceService/Evaluate",
};

std::unique_ptr< InferenceService::Stub> InferenceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InferenceService::Stub> stub(new InferenceService::Stub(channel));
  return stub;
}

InferenceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Evaluate_(InferenceService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status InferenceService::Stub::Evaluate(::grpc::ClientContext* context, const ::inference::BatchInferenceRequest& request, ::inference::BatchInferenceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Evaluate_, context, request, response);
}

void InferenceService::Stub::experimental_async::Evaluate(::grpc::ClientContext* context, const ::inference::BatchInferenceRequest* request, ::inference::BatchInferenceResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Evaluate_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::inference::BatchInferenceResponse>* InferenceService::Stub::AsyncEvaluateRaw(::grpc::ClientContext* context, const ::inference::BatchInferenceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::inference::BatchInferenceResponse>::Create(channel_.get(), cq, rpcmethod_Evaluate_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::inference::BatchInferenceResponse>* InferenceService::Stub::PrepareAsyncEvaluateRaw(::grpc::ClientContext* context, const ::inference::BatchInferenceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::inference::BatchInferenceResponse>::Create(channel_.get(), cq, rpcmethod_Evaluate_, context, request, false);
}

InferenceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InferenceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InferenceService::Service, ::inference::BatchInferenceRequest, ::inference::BatchInferenceResponse>(
          std::mem_fn(&InferenceService::Service::Evaluate), this)));
}

InferenceService::Service::~Service() {
}

::grpc::Status InferenceService::Service::Evaluate(::grpc::ServerContext* context, const ::inference::BatchInferenceRequest* request, ::inference::BatchInferenceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace inference

