// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inference.proto
// Protobuf C++ Version: 6.31.1

#ifndef inference_2eproto_2epb_2eh
#define inference_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_inference_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_inference_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_inference_2eproto;
}  // extern "C"
namespace inference {
class BatchInferenceRequest;
struct BatchInferenceRequestDefaultTypeInternal;
extern BatchInferenceRequestDefaultTypeInternal _BatchInferenceRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BatchInferenceRequest_class_data_;
class BatchInferenceResponse;
struct BatchInferenceResponseDefaultTypeInternal;
extern BatchInferenceResponseDefaultTypeInternal _BatchInferenceResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BatchInferenceResponse_class_data_;
class Evaluation;
struct EvaluationDefaultTypeInternal;
extern EvaluationDefaultTypeInternal _Evaluation_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Evaluation_class_data_;
class PositionTensor;
struct PositionTensorDefaultTypeInternal;
extern PositionTensorDefaultTypeInternal _PositionTensor_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PositionTensor_class_data_;
}  // namespace inference
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace inference {

// ===================================================================


// -------------------------------------------------------------------

class PositionTensor final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:inference.PositionTensor) */ {
 public:
  inline PositionTensor() : PositionTensor(nullptr) {}
  ~PositionTensor() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PositionTensor* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PositionTensor));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PositionTensor(::google::protobuf::internal::ConstantInitialized);

  inline PositionTensor(const PositionTensor& from) : PositionTensor(nullptr, from) {}
  inline PositionTensor(PositionTensor&& from) noexcept
      : PositionTensor(nullptr, ::std::move(from)) {}
  inline PositionTensor& operator=(const PositionTensor& from) {
    CopyFrom(from);
    return *this;
  }
  inline PositionTensor& operator=(PositionTensor&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PositionTensor& default_instance() {
    return *reinterpret_cast<const PositionTensor*>(
        &_PositionTensor_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PositionTensor& a, PositionTensor& b) { a.Swap(&b); }
  inline void Swap(PositionTensor* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PositionTensor* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PositionTensor* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PositionTensor>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PositionTensor& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PositionTensor& from) { PositionTensor::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PositionTensor* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "inference.PositionTensor"; }

 protected:
  explicit PositionTensor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PositionTensor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PositionTensor& from);
  PositionTensor(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PositionTensor&& from) noexcept
      : PositionTensor(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBoardStateFieldNumber = 1,
  };
  // repeated float board_state = 1 [packed = true];
  int board_state_size() const;
  private:
  int _internal_board_state_size() const;

  public:
  void clear_board_state() ;
  float board_state(int index) const;
  void set_board_state(int index, float value);
  void add_board_state(float value);
  const ::google::protobuf::RepeatedField<float>& board_state() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_board_state();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_board_state() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_board_state();

  public:
  // @@protoc_insertion_point(class_scope:inference.PositionTensor)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PositionTensor& from_msg);
    ::google::protobuf::RepeatedField<float> board_state_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PositionTensor_class_data_;
// -------------------------------------------------------------------

class Evaluation final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:inference.Evaluation) */ {
 public:
  inline Evaluation() : Evaluation(nullptr) {}
  ~Evaluation() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Evaluation* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Evaluation));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Evaluation(::google::protobuf::internal::ConstantInitialized);

  inline Evaluation(const Evaluation& from) : Evaluation(nullptr, from) {}
  inline Evaluation(Evaluation&& from) noexcept
      : Evaluation(nullptr, ::std::move(from)) {}
  inline Evaluation& operator=(const Evaluation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Evaluation& operator=(Evaluation&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Evaluation& default_instance() {
    return *reinterpret_cast<const Evaluation*>(
        &_Evaluation_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Evaluation& a, Evaluation& b) { a.Swap(&b); }
  inline void Swap(Evaluation* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Evaluation* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Evaluation* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Evaluation>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Evaluation& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Evaluation& from) { Evaluation::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Evaluation* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "inference.Evaluation"; }

 protected:
  explicit Evaluation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Evaluation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Evaluation& from);
  Evaluation(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Evaluation&& from) noexcept
      : Evaluation(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPolicyLogitsFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // repeated float policy_logits = 1 [packed = true];
  int policy_logits_size() const;
  private:
  int _internal_policy_logits_size() const;

  public:
  void clear_policy_logits() ;
  float policy_logits(int index) const;
  void set_policy_logits(int index, float value);
  void add_policy_logits(float value);
  const ::google::protobuf::RepeatedField<float>& policy_logits() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_policy_logits();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_policy_logits() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_policy_logits();

  public:
  // float value = 2;
  void clear_value() ;
  float value() const;
  void set_value(float value);

  private:
  float _internal_value() const;
  void _internal_set_value(float value);

  public:
  // @@protoc_insertion_point(class_scope:inference.Evaluation)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Evaluation& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> policy_logits_;
    float value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Evaluation_class_data_;
// -------------------------------------------------------------------

class BatchInferenceResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:inference.BatchInferenceResponse) */ {
 public:
  inline BatchInferenceResponse() : BatchInferenceResponse(nullptr) {}
  ~BatchInferenceResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BatchInferenceResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BatchInferenceResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BatchInferenceResponse(::google::protobuf::internal::ConstantInitialized);

  inline BatchInferenceResponse(const BatchInferenceResponse& from) : BatchInferenceResponse(nullptr, from) {}
  inline BatchInferenceResponse(BatchInferenceResponse&& from) noexcept
      : BatchInferenceResponse(nullptr, ::std::move(from)) {}
  inline BatchInferenceResponse& operator=(const BatchInferenceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BatchInferenceResponse& operator=(BatchInferenceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BatchInferenceResponse& default_instance() {
    return *reinterpret_cast<const BatchInferenceResponse*>(
        &_BatchInferenceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(BatchInferenceResponse& a, BatchInferenceResponse& b) { a.Swap(&b); }
  inline void Swap(BatchInferenceResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BatchInferenceResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BatchInferenceResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BatchInferenceResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BatchInferenceResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BatchInferenceResponse& from) { BatchInferenceResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BatchInferenceResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "inference.BatchInferenceResponse"; }

 protected:
  explicit BatchInferenceResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BatchInferenceResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BatchInferenceResponse& from);
  BatchInferenceResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BatchInferenceResponse&& from) noexcept
      : BatchInferenceResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEvaluationsFieldNumber = 1,
  };
  // repeated .inference.Evaluation evaluations = 1;
  int evaluations_size() const;
  private:
  int _internal_evaluations_size() const;

  public:
  void clear_evaluations() ;
  ::inference::Evaluation* PROTOBUF_NONNULL mutable_evaluations(int index);
  ::google::protobuf::RepeatedPtrField<::inference::Evaluation>* PROTOBUF_NONNULL mutable_evaluations();

  private:
  const ::google::protobuf::RepeatedPtrField<::inference::Evaluation>& _internal_evaluations() const;
  ::google::protobuf::RepeatedPtrField<::inference::Evaluation>* PROTOBUF_NONNULL _internal_mutable_evaluations();
  public:
  const ::inference::Evaluation& evaluations(int index) const;
  ::inference::Evaluation* PROTOBUF_NONNULL add_evaluations();
  const ::google::protobuf::RepeatedPtrField<::inference::Evaluation>& evaluations() const;
  // @@protoc_insertion_point(class_scope:inference.BatchInferenceResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BatchInferenceResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::inference::Evaluation > evaluations_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BatchInferenceResponse_class_data_;
// -------------------------------------------------------------------

class BatchInferenceRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:inference.BatchInferenceRequest) */ {
 public:
  inline BatchInferenceRequest() : BatchInferenceRequest(nullptr) {}
  ~BatchInferenceRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BatchInferenceRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BatchInferenceRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BatchInferenceRequest(::google::protobuf::internal::ConstantInitialized);

  inline BatchInferenceRequest(const BatchInferenceRequest& from) : BatchInferenceRequest(nullptr, from) {}
  inline BatchInferenceRequest(BatchInferenceRequest&& from) noexcept
      : BatchInferenceRequest(nullptr, ::std::move(from)) {}
  inline BatchInferenceRequest& operator=(const BatchInferenceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BatchInferenceRequest& operator=(BatchInferenceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BatchInferenceRequest& default_instance() {
    return *reinterpret_cast<const BatchInferenceRequest*>(
        &_BatchInferenceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(BatchInferenceRequest& a, BatchInferenceRequest& b) { a.Swap(&b); }
  inline void Swap(BatchInferenceRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BatchInferenceRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BatchInferenceRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BatchInferenceRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BatchInferenceRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BatchInferenceRequest& from) { BatchInferenceRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BatchInferenceRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "inference.BatchInferenceRequest"; }

 protected:
  explicit BatchInferenceRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BatchInferenceRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BatchInferenceRequest& from);
  BatchInferenceRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BatchInferenceRequest&& from) noexcept
      : BatchInferenceRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionsFieldNumber = 1,
  };
  // repeated .inference.PositionTensor positions = 1;
  int positions_size() const;
  private:
  int _internal_positions_size() const;

  public:
  void clear_positions() ;
  ::inference::PositionTensor* PROTOBUF_NONNULL mutable_positions(int index);
  ::google::protobuf::RepeatedPtrField<::inference::PositionTensor>* PROTOBUF_NONNULL mutable_positions();

  private:
  const ::google::protobuf::RepeatedPtrField<::inference::PositionTensor>& _internal_positions() const;
  ::google::protobuf::RepeatedPtrField<::inference::PositionTensor>* PROTOBUF_NONNULL _internal_mutable_positions();
  public:
  const ::inference::PositionTensor& positions(int index) const;
  ::inference::PositionTensor* PROTOBUF_NONNULL add_positions();
  const ::google::protobuf::RepeatedPtrField<::inference::PositionTensor>& positions() const;
  // @@protoc_insertion_point(class_scope:inference.BatchInferenceRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BatchInferenceRequest& from_msg);
    ::google::protobuf::RepeatedPtrField< ::inference::PositionTensor > positions_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BatchInferenceRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PositionTensor

// repeated float board_state = 1 [packed = true];
inline int PositionTensor::_internal_board_state_size() const {
  return _internal_board_state().size();
}
inline int PositionTensor::board_state_size() const {
  return _internal_board_state_size();
}
inline void PositionTensor::clear_board_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.board_state_.Clear();
}
inline float PositionTensor::board_state(int index) const {
  // @@protoc_insertion_point(field_get:inference.PositionTensor.board_state)
  return _internal_board_state().Get(index);
}
inline void PositionTensor::set_board_state(int index, float value) {
  _internal_mutable_board_state()->Set(index, value);
  // @@protoc_insertion_point(field_set:inference.PositionTensor.board_state)
}
inline void PositionTensor::add_board_state(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_board_state()->Add(value);
  // @@protoc_insertion_point(field_add:inference.PositionTensor.board_state)
}
inline const ::google::protobuf::RepeatedField<float>& PositionTensor::board_state() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:inference.PositionTensor.board_state)
  return _internal_board_state();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL PositionTensor::mutable_board_state()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:inference.PositionTensor.board_state)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_board_state();
}
inline const ::google::protobuf::RepeatedField<float>&
PositionTensor::_internal_board_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.board_state_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
PositionTensor::_internal_mutable_board_state() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.board_state_;
}

// -------------------------------------------------------------------

// Evaluation

// repeated float policy_logits = 1 [packed = true];
inline int Evaluation::_internal_policy_logits_size() const {
  return _internal_policy_logits().size();
}
inline int Evaluation::policy_logits_size() const {
  return _internal_policy_logits_size();
}
inline void Evaluation::clear_policy_logits() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.policy_logits_.Clear();
}
inline float Evaluation::policy_logits(int index) const {
  // @@protoc_insertion_point(field_get:inference.Evaluation.policy_logits)
  return _internal_policy_logits().Get(index);
}
inline void Evaluation::set_policy_logits(int index, float value) {
  _internal_mutable_policy_logits()->Set(index, value);
  // @@protoc_insertion_point(field_set:inference.Evaluation.policy_logits)
}
inline void Evaluation::add_policy_logits(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_policy_logits()->Add(value);
  // @@protoc_insertion_point(field_add:inference.Evaluation.policy_logits)
}
inline const ::google::protobuf::RepeatedField<float>& Evaluation::policy_logits() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:inference.Evaluation.policy_logits)
  return _internal_policy_logits();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL Evaluation::mutable_policy_logits()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:inference.Evaluation.policy_logits)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_policy_logits();
}
inline const ::google::protobuf::RepeatedField<float>&
Evaluation::_internal_policy_logits() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.policy_logits_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
Evaluation::_internal_mutable_policy_logits() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.policy_logits_;
}

// float value = 2;
inline void Evaluation::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float Evaluation::value() const {
  // @@protoc_insertion_point(field_get:inference.Evaluation.value)
  return _internal_value();
}
inline void Evaluation::set_value(float value) {
  _internal_set_value(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:inference.Evaluation.value)
}
inline float Evaluation::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_;
}
inline void Evaluation::_internal_set_value(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = value;
}

// -------------------------------------------------------------------

// BatchInferenceRequest

// repeated .inference.PositionTensor positions = 1;
inline int BatchInferenceRequest::_internal_positions_size() const {
  return _internal_positions().size();
}
inline int BatchInferenceRequest::positions_size() const {
  return _internal_positions_size();
}
inline void BatchInferenceRequest::clear_positions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.positions_.Clear();
}
inline ::inference::PositionTensor* PROTOBUF_NONNULL BatchInferenceRequest::mutable_positions(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:inference.BatchInferenceRequest.positions)
  return _internal_mutable_positions()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::inference::PositionTensor>* PROTOBUF_NONNULL BatchInferenceRequest::mutable_positions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:inference.BatchInferenceRequest.positions)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_positions();
}
inline const ::inference::PositionTensor& BatchInferenceRequest::positions(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:inference.BatchInferenceRequest.positions)
  return _internal_positions().Get(index);
}
inline ::inference::PositionTensor* PROTOBUF_NONNULL BatchInferenceRequest::add_positions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::inference::PositionTensor* _add = _internal_mutable_positions()->Add();
  // @@protoc_insertion_point(field_add:inference.BatchInferenceRequest.positions)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::inference::PositionTensor>& BatchInferenceRequest::positions() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:inference.BatchInferenceRequest.positions)
  return _internal_positions();
}
inline const ::google::protobuf::RepeatedPtrField<::inference::PositionTensor>&
BatchInferenceRequest::_internal_positions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.positions_;
}
inline ::google::protobuf::RepeatedPtrField<::inference::PositionTensor>* PROTOBUF_NONNULL
BatchInferenceRequest::_internal_mutable_positions() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.positions_;
}

// -------------------------------------------------------------------

// BatchInferenceResponse

// repeated .inference.Evaluation evaluations = 1;
inline int BatchInferenceResponse::_internal_evaluations_size() const {
  return _internal_evaluations().size();
}
inline int BatchInferenceResponse::evaluations_size() const {
  return _internal_evaluations_size();
}
inline void BatchInferenceResponse::clear_evaluations() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.evaluations_.Clear();
}
inline ::inference::Evaluation* PROTOBUF_NONNULL BatchInferenceResponse::mutable_evaluations(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:inference.BatchInferenceResponse.evaluations)
  return _internal_mutable_evaluations()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::inference::Evaluation>* PROTOBUF_NONNULL BatchInferenceResponse::mutable_evaluations()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:inference.BatchInferenceResponse.evaluations)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_evaluations();
}
inline const ::inference::Evaluation& BatchInferenceResponse::evaluations(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:inference.BatchInferenceResponse.evaluations)
  return _internal_evaluations().Get(index);
}
inline ::inference::Evaluation* PROTOBUF_NONNULL BatchInferenceResponse::add_evaluations()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::inference::Evaluation* _add = _internal_mutable_evaluations()->Add();
  // @@protoc_insertion_point(field_add:inference.BatchInferenceResponse.evaluations)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::inference::Evaluation>& BatchInferenceResponse::evaluations() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:inference.BatchInferenceResponse.evaluations)
  return _internal_evaluations();
}
inline const ::google::protobuf::RepeatedPtrField<::inference::Evaluation>&
BatchInferenceResponse::_internal_evaluations() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.evaluations_;
}
inline ::google::protobuf::RepeatedPtrField<::inference::Evaluation>* PROTOBUF_NONNULL
BatchInferenceResponse::_internal_mutable_evaluations() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.evaluations_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace inference


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // inference_2eproto_2epb_2eh
