// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inference.proto

#include "inference.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace inference {
PROTOBUF_CONSTEXPR PositionTensor::PositionTensor(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.board_state_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PositionTensorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PositionTensorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PositionTensorDefaultTypeInternal() {}
  union {
    PositionTensor _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PositionTensorDefaultTypeInternal _PositionTensor_default_instance_;
PROTOBUF_CONSTEXPR BatchInferenceRequest::BatchInferenceRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.positions_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BatchInferenceRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BatchInferenceRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BatchInferenceRequestDefaultTypeInternal() {}
  union {
    BatchInferenceRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BatchInferenceRequestDefaultTypeInternal _BatchInferenceRequest_default_instance_;
PROTOBUF_CONSTEXPR EvaluationResult::EvaluationResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.policy_logits_)*/{}
  , /*decltype(_impl_.value_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EvaluationResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EvaluationResultDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EvaluationResultDefaultTypeInternal() {}
  union {
    EvaluationResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EvaluationResultDefaultTypeInternal _EvaluationResult_default_instance_;
PROTOBUF_CONSTEXPR BatchInferenceResponse::BatchInferenceResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.evaluations_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BatchInferenceResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BatchInferenceResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BatchInferenceResponseDefaultTypeInternal() {}
  union {
    BatchInferenceResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BatchInferenceResponseDefaultTypeInternal _BatchInferenceResponse_default_instance_;
}  // namespace inference
static ::_pb::Metadata file_level_metadata_inference_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_inference_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_inference_2eproto = nullptr;

const uint32_t TableStruct_inference_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inference::PositionTensor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::inference::PositionTensor, _impl_.board_state_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inference::BatchInferenceRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::inference::BatchInferenceRequest, _impl_.positions_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inference::EvaluationResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::inference::EvaluationResult, _impl_.policy_logits_),
  PROTOBUF_FIELD_OFFSET(::inference::EvaluationResult, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::inference::BatchInferenceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::inference::BatchInferenceResponse, _impl_.evaluations_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::inference::PositionTensor)},
  { 7, -1, -1, sizeof(::inference::BatchInferenceRequest)},
  { 14, -1, -1, sizeof(::inference::EvaluationResult)},
  { 22, -1, -1, sizeof(::inference::BatchInferenceResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::inference::_PositionTensor_default_instance_._instance,
  &::inference::_BatchInferenceRequest_default_instance_._instance,
  &::inference::_EvaluationResult_default_instance_._instance,
  &::inference::_BatchInferenceResponse_default_instance_._instance,
};

const char descriptor_table_protodef_inference_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017inference.proto\022\tinference\"%\n\016Position"
  "Tensor\022\023\n\013board_state\030\001 \003(\002\"E\n\025BatchInfe"
  "renceRequest\022,\n\tpositions\030\001 \003(\0132\031.infere"
  "nce.PositionTensor\"8\n\020EvaluationResult\022\025"
  "\n\rpolicy_logits\030\001 \003(\002\022\r\n\005value\030\002 \001(\002\"J\n\026"
  "BatchInferenceResponse\0220\n\013evaluations\030\001 "
  "\003(\0132\033.inference.EvaluationResult2c\n\020Infe"
  "renceService\022O\n\010Evaluate\022 .inference.Bat"
  "chInferenceRequest\032!.inference.BatchInfe"
  "renceResponseb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_inference_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_inference_2eproto = {
    false, false, 381, descriptor_table_protodef_inference_2eproto,
    "inference.proto",
    &descriptor_table_inference_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_inference_2eproto::offsets,
    file_level_metadata_inference_2eproto, file_level_enum_descriptors_inference_2eproto,
    file_level_service_descriptors_inference_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_inference_2eproto_getter() {
  return &descriptor_table_inference_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_inference_2eproto(&descriptor_table_inference_2eproto);
namespace inference {

// ===================================================================

class PositionTensor::_Internal {
 public:
};

PositionTensor::PositionTensor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:inference.PositionTensor)
}
PositionTensor::PositionTensor(const PositionTensor& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PositionTensor* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.board_state_){from._impl_.board_state_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:inference.PositionTensor)
}

inline void PositionTensor::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.board_state_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PositionTensor::~PositionTensor() {
  // @@protoc_insertion_point(destructor:inference.PositionTensor)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PositionTensor::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.board_state_.~RepeatedField();
}

void PositionTensor::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PositionTensor::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.PositionTensor)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.board_state_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PositionTensor::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated float board_state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_board_state(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 13) {
          _internal_add_board_state(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PositionTensor::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:inference.PositionTensor)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float board_state = 1;
  if (this->_internal_board_state_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_board_state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.PositionTensor)
  return target;
}

size_t PositionTensor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.PositionTensor)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float board_state = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_board_state_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PositionTensor::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PositionTensor::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PositionTensor::GetClassData() const { return &_class_data_; }


void PositionTensor::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PositionTensor*>(&to_msg);
  auto& from = static_cast<const PositionTensor&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:inference.PositionTensor)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.board_state_.MergeFrom(from._impl_.board_state_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PositionTensor::CopyFrom(const PositionTensor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.PositionTensor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PositionTensor::IsInitialized() const {
  return true;
}

void PositionTensor::InternalSwap(PositionTensor* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.board_state_.InternalSwap(&other->_impl_.board_state_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PositionTensor::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_inference_2eproto_getter, &descriptor_table_inference_2eproto_once,
      file_level_metadata_inference_2eproto[0]);
}

// ===================================================================

class BatchInferenceRequest::_Internal {
 public:
};

BatchInferenceRequest::BatchInferenceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:inference.BatchInferenceRequest)
}
BatchInferenceRequest::BatchInferenceRequest(const BatchInferenceRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BatchInferenceRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.positions_){from._impl_.positions_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:inference.BatchInferenceRequest)
}

inline void BatchInferenceRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.positions_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BatchInferenceRequest::~BatchInferenceRequest() {
  // @@protoc_insertion_point(destructor:inference.BatchInferenceRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BatchInferenceRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.positions_.~RepeatedPtrField();
}

void BatchInferenceRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BatchInferenceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.BatchInferenceRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.positions_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BatchInferenceRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .inference.PositionTensor positions = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_positions(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BatchInferenceRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:inference.BatchInferenceRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .inference.PositionTensor positions = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_positions_size()); i < n; i++) {
    const auto& repfield = this->_internal_positions(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.BatchInferenceRequest)
  return target;
}

size_t BatchInferenceRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.BatchInferenceRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .inference.PositionTensor positions = 1;
  total_size += 1UL * this->_internal_positions_size();
  for (const auto& msg : this->_impl_.positions_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BatchInferenceRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BatchInferenceRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BatchInferenceRequest::GetClassData() const { return &_class_data_; }


void BatchInferenceRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BatchInferenceRequest*>(&to_msg);
  auto& from = static_cast<const BatchInferenceRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:inference.BatchInferenceRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.positions_.MergeFrom(from._impl_.positions_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BatchInferenceRequest::CopyFrom(const BatchInferenceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.BatchInferenceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BatchInferenceRequest::IsInitialized() const {
  return true;
}

void BatchInferenceRequest::InternalSwap(BatchInferenceRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.positions_.InternalSwap(&other->_impl_.positions_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BatchInferenceRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_inference_2eproto_getter, &descriptor_table_inference_2eproto_once,
      file_level_metadata_inference_2eproto[1]);
}

// ===================================================================

class EvaluationResult::_Internal {
 public:
};

EvaluationResult::EvaluationResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:inference.EvaluationResult)
}
EvaluationResult::EvaluationResult(const EvaluationResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EvaluationResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.policy_logits_){from._impl_.policy_logits_}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.value_ = from._impl_.value_;
  // @@protoc_insertion_point(copy_constructor:inference.EvaluationResult)
}

inline void EvaluationResult::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.policy_logits_){arena}
    , decltype(_impl_.value_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

EvaluationResult::~EvaluationResult() {
  // @@protoc_insertion_point(destructor:inference.EvaluationResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EvaluationResult::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.policy_logits_.~RepeatedField();
}

void EvaluationResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EvaluationResult::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.EvaluationResult)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.policy_logits_.Clear();
  _impl_.value_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EvaluationResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated float policy_logits = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_policy_logits(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 13) {
          _internal_add_policy_logits(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EvaluationResult::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:inference.EvaluationResult)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float policy_logits = 1;
  if (this->_internal_policy_logits_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_policy_logits(), target);
  }

  // float value = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_value = this->_internal_value();
  uint32_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.EvaluationResult)
  return target;
}

size_t EvaluationResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.EvaluationResult)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float policy_logits = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_policy_logits_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // float value = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_value = this->_internal_value();
  uint32_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EvaluationResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EvaluationResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EvaluationResult::GetClassData() const { return &_class_data_; }


void EvaluationResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EvaluationResult*>(&to_msg);
  auto& from = static_cast<const EvaluationResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:inference.EvaluationResult)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.policy_logits_.MergeFrom(from._impl_.policy_logits_);
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_value = from._internal_value();
  uint32_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EvaluationResult::CopyFrom(const EvaluationResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.EvaluationResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EvaluationResult::IsInitialized() const {
  return true;
}

void EvaluationResult::InternalSwap(EvaluationResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.policy_logits_.InternalSwap(&other->_impl_.policy_logits_);
  swap(_impl_.value_, other->_impl_.value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EvaluationResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_inference_2eproto_getter, &descriptor_table_inference_2eproto_once,
      file_level_metadata_inference_2eproto[2]);
}

// ===================================================================

class BatchInferenceResponse::_Internal {
 public:
};

BatchInferenceResponse::BatchInferenceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:inference.BatchInferenceResponse)
}
BatchInferenceResponse::BatchInferenceResponse(const BatchInferenceResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BatchInferenceResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.evaluations_){from._impl_.evaluations_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:inference.BatchInferenceResponse)
}

inline void BatchInferenceResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.evaluations_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BatchInferenceResponse::~BatchInferenceResponse() {
  // @@protoc_insertion_point(destructor:inference.BatchInferenceResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BatchInferenceResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.evaluations_.~RepeatedPtrField();
}

void BatchInferenceResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BatchInferenceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.BatchInferenceResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.evaluations_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BatchInferenceResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .inference.EvaluationResult evaluations = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_evaluations(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BatchInferenceResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:inference.BatchInferenceResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .inference.EvaluationResult evaluations = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_evaluations_size()); i < n; i++) {
    const auto& repfield = this->_internal_evaluations(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.BatchInferenceResponse)
  return target;
}

size_t BatchInferenceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.BatchInferenceResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .inference.EvaluationResult evaluations = 1;
  total_size += 1UL * this->_internal_evaluations_size();
  for (const auto& msg : this->_impl_.evaluations_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BatchInferenceResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BatchInferenceResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BatchInferenceResponse::GetClassData() const { return &_class_data_; }


void BatchInferenceResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BatchInferenceResponse*>(&to_msg);
  auto& from = static_cast<const BatchInferenceResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:inference.BatchInferenceResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.evaluations_.MergeFrom(from._impl_.evaluations_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BatchInferenceResponse::CopyFrom(const BatchInferenceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.BatchInferenceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BatchInferenceResponse::IsInitialized() const {
  return true;
}

void BatchInferenceResponse::InternalSwap(BatchInferenceResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.evaluations_.InternalSwap(&other->_impl_.evaluations_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BatchInferenceResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_inference_2eproto_getter, &descriptor_table_inference_2eproto_once,
      file_level_metadata_inference_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace inference
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::inference::PositionTensor*
Arena::CreateMaybeMessage< ::inference::PositionTensor >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inference::PositionTensor >(arena);
}
template<> PROTOBUF_NOINLINE ::inference::BatchInferenceRequest*
Arena::CreateMaybeMessage< ::inference::BatchInferenceRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inference::BatchInferenceRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::inference::EvaluationResult*
Arena::CreateMaybeMessage< ::inference::EvaluationResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inference::EvaluationResult >(arena);
}
template<> PROTOBUF_NOINLINE ::inference::BatchInferenceResponse*
Arena::CreateMaybeMessage< ::inference::BatchInferenceResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::inference::BatchInferenceResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
